### PR TITLE
Add pylightning package

### PR DESCRIPTION
**Pull request by jonasnick**
Allows to add clightning plugins in the future (or in private forks).

### CODE REVIEW

**Comment by jb55** [comment]
perhaps we should just upstream this? looks simple enough.

**Comment by jonasnick** [comment]
Not sure if I want to commit to maintaining too many upstream packages. I don't see a downside to merging this first, then upstream it when convenient.

**Comment by jonasnick** [comment]
Thanks. Cherry-picked.

**Comment by jb55** [comment]
```
-----BEGIN OPENTIMESTAMPS MESSAGE-----

- -----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

ACK 22fcd47fe552112a06d77bd2ff8c59bfd9f2ebba

tested import with:

  nix-shell -p 'with (import ./. {}); python3.withPackages (p: [ pylightning p.libagent ])'

and

  nix-shell -p '(import ./. {}).pylightning'
- -----BEGIN PGP SIGNATURE-----

iIQEARYKACwWIQRbKx5PYiFrx0NirGHU+6L8RTWiqQUCXTnpzw4camI1NUBqYjU1
LmNvbQAKCRDU+6L8RTWiqd6vAPsGU4hwVHIt5MUmCpM5csO7w3rYwP2UZYX8nRRT
hrB5ygEA0KDO/QnfQl2PLrDTqbawq+hHzSHIYocpctDPjrtZkQ8=
=5ob5
- -----END PGP SIGNATURE-----

-----BEGIN OPENTIMESTAMPS PROOF-----

AE9wZW5UaW1lc3RhbXBzAABQcm9vZgC/ieLohOiSlAEI48N/Bw9uKQ5dFp8rRVKjzI6xSHCZaLQR
wgbpJFhJoF/wEAlaKZBPnmKjQ35zxhCEEqwI//AQOT2Ti+hLRY8JFdodXltHLAjxBF056efwCOIa
O9QAflZZAIPf4w0u+QyOLCtodHRwczovL2JvYi5idGMuY2FsZW5kYXIub3BlbnRpbWVzdGFtcHMu
b3Jn//AQQSwaPCt3bHgT5ePnahQAogjxBF056ejwCP63IQw79k0GAIPf4w0u+QyOIyJodHRwczov
L2J0Yy5jYWxlbmRhci5jYXRhbGxheHkuY29t//AQVthQpcQqJPDuYGS4nd0LNAjxBF056efwCIPY
go39W0asAIPf4w0u+QyOLi1odHRwczovL2FsaWNlLmJ0Yy5jYWxlbmRhci5vcGVudGltZXN0YW1w
cy5vcmfwEHEfH374D4M5Lp0D6OUuZ9AI8QRdOenn8AhqL6Btbmxd9ACD3+MNLvkMjikoaHR0cHM6
Ly9maW5uZXkuY2FsZW5kYXIuZXRlcm5pdHl3YWxsLmNvbQ==
-----END OPENTIMESTAMPS PROOF-----
```

this is a bit over the top, but I wanted to try using my [ots tooling](https://github.com/jb55/ots-tools) a bit more.

to verify:

```
xclip -o | ./otsclear -v | gpg --verify
```

**Comment by nixbitcoin** [comment]
Why are you not doing the python checks?

**Comment by jonasnick** [comment]
Looks like that line isn't doing anything anyway, removed it.

**Pull request merged**
