### PR TITLE
Remove bitcoind banlist

### PR DESCRIPTION
**Pull request by erikarvstedt**
Gmaxwell's banlist (https://people.xiph.org/~greg/banlist.cli.txt) is no longer maintained and hasn't been updated since 2 years.

### CODE REVIEW

**Comment by nixbitcoin** [comment]
I would wait until https://github.com/dgarage/NBXplorer/commit/cd1f5df74944c6584a8df6b4427e97ece8db2669 lands in the next NBXplorer release before adding a manual patch here.

**Comment by erikarvstedt** [comment]
I didn't expect this to get fixed so fast. 😄 
Would you be okay with adding the upstream patch?

**Comment by nixbitcoin** [comment]
Better. But why the rush? You'll have to undo the patch anyway soon.

**Comment by erikarvstedt** [comment]
Because this speeds up the test. I've removed the nbxplorer patch.

**Comment by Kixunil** [comment]
FYI NBXplorer just works if you forbid `setban` in Core premissions.

**Comment by erikarvstedt** [comment]
@Kixunil, thanks, nbxplorer was indeed never allowed to `setban` because it has only `bitcoinrpc-public` permissions.

**Review by nixbitcoin — COMMENTED** [review]
ACK 8dc4858872edea4cb91768163ec9cd878ca0f06b

**Review by nixbitcoin — APPROVED** [review]
ACK 8dc4858872edea4cb91768163ec9cd878ca0f06b

**Review by jonasnick — APPROVED** [review]
ACK 8dc4858872edea4cb91768163ec9cd878ca0f06b

**Pull request merged**
