### PR TITLE
Removed reference to file that does not exist

### PR DESCRIPTION
**Pull request by galderz**

### CODE REVIEW

**Review by jonasnick — COMMENTED** [review]
The file should exist after being created in step 4.1.

**Comment by erikarvstedt** [comment]
The file is copied from `examples/nixops/node-vbox.nix` in step 3.

**Comment by erikarvstedt** [comment]
Retracted my incorrect comment. @jonasnick is right.
The manual would be clearer if the file were renamed to `node-target.nix`.

**Comment by erikarvstedt** [comment]
Superseded by #296.

**Comment by galderz** [comment]
I don't know what exactly happened, but when I copied over files, i ended up a `nixops/node.nix` that contained:

```
  bitcoin-node = { config, pkgs, lib, ... }: {
    imports = [
      ../configuration.nix
      <nix-bitcoin/modules/deployment/nixops.nix>
    ];
```

So, the actual configuration is in a `configuration.nix` file at the root of the node folder.

**Pull request closed without merging**
