### PR TITLE
Fix containers

### PR DESCRIPTION
**Pull request by erikarvstedt**
#### Commit `generate-secrets: use pwgen`

To compare the password output, run
```
nix run -f '<nixpkgs>' apg -c apg -m 20 -x 20 -M Ncl -n 1
nix run -f '<nixpkgs>' pwgen -c pwgen -s 20 1
```

#### Commit `extra-container: 0.5-pre -> 0.5`

Use this for auditing:
```
tmp=$(mktemp -d -p /tmp)
mkdir -p $tmp/{old,new}
fetchAndCheck() {
    local url=https://github.com/erikarvstedt/extra-container/archive/$1.tar.gz
    curl -sSL $url | tar xz --strip-components=1 -C $2;
    echo "sha256 for $1 is $(nix hash-path --base32 "$2")"
}
fetchAndCheck 0.5-pre $tmp/old
fetchAndCheck 0.5     $tmp/new
git diff --no-index $tmp/{old,new}
rm -rf $tmp
```

### CODE REVIEW

**Comment by nixbitcoin** [comment]
[Fixup](https://github.com/nixbitcoin/nix-bitcoin/commits/fix-containers-nb)

**Comment by erikarvstedt** [comment]
Thanks!

**Comment by nixbitcoin** [comment]
Interestingly, ẁhile testing this PR I noticed I was getting

```
Job for container@demo-node.service canceled.
Died at /nix/store/wjciyjb5i5rjnjz48zqp57hf0xb9kgyk-nixos-container/bin/nixos-container line 191.
```
when running `examples/deploy-container.sh`

I cycled through all the recent commits and figured out the breaking change was introduced in b2a7158c4eecd51c1db332151371b5168bfabe8d. Any idea how to further troubleshoot?

**Comment by erikarvstedt** [comment]
Thanks for catching this. 
It was the `scudo` memory allocator bug again.

**Comment by erikarvstedt** [comment]
I'll prepare a channel update PR later today to pull in the fix.

**Comment by erikarvstedt** [comment]
The scudo bug breaks some services like clightning, regardless of the deployment mode.
Also, it turned out that the backport of the fix has no effects on 20.09.
I've added a workaround to this PR.

If you're interested in fixing scudo for 20.09, I'd recommend raising this issue upstream.

**Review by nixbitcoin — APPROVED** [review]
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

ACK 870e14eb0f65ac1ed229da7b679be85c2832567f
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCgAdFiEEV3o0Un8+KoXoD+Fk3RH5rVMIs7oFAl/cZDAACgkQ3RH5rVMI
s7riiA//R91xcaxfjqgT/UkXIXq+S/Ibehr4SkW80ZBWtXoLH4LFDnUeN45Hws01
7ydqhTkL9ct9Vb8nHj4yttNpZyzAj0NZyZ1Jt7VrC13INEJhJsGQrd9nmcXQakQ/
W7yyiNV6JFr5UWYUUugDLVGk9N0f87kPe66kFv5MKaLV6iWMmCGugnP1GYfqN4cX
HTWnhFODoFDwcIfzFhzK2+N4sMxuXRCyPzgrHFD7SH50IdAUwYv+AnfiWxG/d4Wo
Ukpvnxkscpq20UkA961Lx9IXAleBYLBH6gxWXURpG44gHF8C5LDS/lfGVfY08pzg
ByqCNNhjkUI48pqiprmkENkVLJM7ye8z0q7q4hO2Fy6rZA93iAyuHTBiwv9Z7BOo
n39ppcyy9nnr2SUiCh1l0fDgWFAbefpG7yTErHOM/2dRalkaOqMW95oA0IzhhmOR
KU0Q4WXFekWWHyEkyK3eEI/QsjPXOyIPG3THO3ZDHRqDgOi6RG4nmjvvACuppoH7
8xdNbzoLolh5JMhy39d02+9CJB0xzne3XteMAMe8XO40F7C7hK7lnmYALH6bJjxH
sEWbR2q42Tqt7Bu44gRh22O2+QumysXPQoaQ7+RBOrlPgaNcnS2KY1rowb2fCEP9
EzK85snsTReWpXThCoFIJTd7G5/21OZvmVpJsYM+kHoTqFyjT4c=
=L0Yd
-----END PGP SIGNATURE-----
```

**Comment by nixbitcoin** [comment]
What do you think about using the graphene-hardened malloc?

**Comment by erikarvstedt** [comment]
`graphene-hardened` does work but it roughly doubles the runtime of the `secureNode` test (I'm comparing the `hardened` profile + `libc` with the `hardened` profile + `graphene-hardened`).
I've added a `hardened` test so we have a proper way to test the hardened profile.

**Comment by erikarvstedt** [comment]
I've changed commit `generate-secrets: use pwgen`.
Excerpt from the commit message:
Password length and alphabet is unchanged, but the restriction to include at least one numeric and one capital char has been removed. This restriction is not needed by client applications, adds code complexity, and even (insignificantly) reduces entropy.

**Review by nixbitcoin — APPROVED** [review]
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

ACK 2bfb4efbd8d313725f659983193e26170c2b4881
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCgAdFiEEV3o0Un8+KoXoD+Fk3RH5rVMIs7oFAl/gansACgkQ3RH5rVMI
s7qDYhAAtefZ6YzZSUfK7BuDhaq9nQt7MY0foA4eRo5uV440j8TzEwbQ9OAW0US4
xsMdIVsUryqqQT7VyVmJck5CG3UjImm85Uq/NOzCn+RAlbQGSsdpsMugba6OKl+A
FCkVEgpUi4s++LVWcRaBIRiO5tOXbWviDvGM2LNmLP2LcPWP0nOxmyVAckBc39Ls
P8INxfXPV8K4uGF7wQDZFcHlnkm0Yuo9w82WVruubDqqysImORI7aYHMJbFPWZyH
lal/Ct/FpmnN8BGI20gTncgAylGe0PsmoalvKqmECILPCGCLHx1Mtq9zPzLAM2Fl
gFRHI6aDWKTT2PDd5RartyM/VET8DbF1s9QYBOMvt6Tzbhc5iaDNk3f67pbPrD6T
RbXyvD1MRF1/SxcuHKF13bemTYwKCK7dFI99Yflj8RvMumEwhOrAugTsVoXt0u/6
IgtNkKbKDpsdYhBhJgLOB3Q4YJ+x4iE7WAWRoxb+mYq7K7+10hMc3n1sGT8j9xG/
5jSnEc1GQUJQKxVHRFrJPK/IYT2XcxoF7kKh2ebDcfA2pTA8gsj+ZKF5+6BhibhH
d/TOnHDw8jKVzmz5BgrlfllFeqy3tdI9Ur1ycI9m53Tr+KmmDNNFW7mZbE4alvKv
iYbTPFriSKRWQQE4xufp0wb7rn6GvvbLnIFq7S7bSPOVQI7Vr/Y=
=Ngf1
-----END PGP SIGNATURE-----
```

**Review by jonasnick — COMMENTED** [review]
utACK 2bfb4efbd8d313725f659983193e26170c2b4881

**Pull request merged**
