### PR TITLE
bitcoind-remote: fix quotation marks in preStart script

### PR DESCRIPTION
**Pull request by seberm**
I think there is a small typo in quotation marks.

### CODE REVIEW

**Comment by seberm** [comment]
I think we could also run a shell lint (e.g. [shellcheck](https://github.com/koalaman/shellcheck) across all/most of the scripts in this repository and fix the issues.

It would be also great if we could run shellcheck tests automatically in Cirrus CI for all the generated scripts (e.g. unit's `ExecStart=`, `ExecStartPre=`, `ExecStartPost`, ... options). What do you think?

**Review by erikarvstedt — APPROVED** [review]
This patch is non-functional and fixes no error, but I agree this quoting style adds consistenty with the service scripts.

ACK 03b75a025459685fc6ede4e651be0183138e6bb0

**Comment by erikarvstedt** [comment]
> What do you think?

Concept ACK. Would you like to implement this?

**Comment by seberm** [comment]
> Would you like to implement this?

I'll try to look into it, thanks! :)

**Pull request merged**
