### PR TITLE
Update nixpkgs (lnd 0.10, clightning 0.8.2)

### PR DESCRIPTION
**Pull request by jonasnick**

### CODE REVIEW

**Comment by jonasnick** [comment]
wtf travis.... build is running, but it doesn't show up here

**Comment by nixbitcoin** [comment]
I can see it now

**Comment by jonasnick** [comment]
yeah seems to work after revoking oauth to my account and granting access again

**Comment by jonasnick** [comment]
For futuer reference: https://travis-ci.community/t/github-pr-is-being-built-but-result-is-not-shown/7025

**Comment by jonasnick** [comment]
travis build succeeded but it doesn't update here...

**Pull request merged**
