### PR TITLE
Eliminate startscript.sh in electrs module

### PR DESCRIPTION
**Pull request by stevenroose**
Fixes https://github.com/fort-nix/nix-bitcoin/issues/86.

I'm new to Nix development, so I have no idea how I can test these things easily..
I'm also not super confident in the correctness, so please review thoroughly :)

### CODE REVIEW

**Comment by jonasnick** [comment]
I test PRs like that by deploying to virtualbox as explained in the docs with `electrs` enabled and check its logs.

**Comment by stevenroose** [comment]
Hmm, it seems like the `$()` notation doesn't work inside `ExecStart`... Does it make sense to do this PR then?

**Comment by jonasnick** [comment]
That's probably the reason why I made a startscript in the first place. Sorry for not remembering earlier.

**Comment by nixbitcoin** [comment]
> Hmm, it seems like the $() notation doesn't work inside ExecStart... Does it make sense to do this PR then?

Yes, that seems to be the case. I'm getting the same error. I've created another PR #96 that fixes the problem by placing the electrs startscript in a temporary dir.

**Pull request closed without merging**
