### PR TITLE
Pkg updates

### PR DESCRIPTION
**Pull request by erikarvstedt**
#### extra-container: 0.5 -> 0.6
Changelog
```
- Add compatibility with current NixOS unstable.
- `extra.exposeLocalhost`: don't fail when iptables lock can't be obtained immediately.
- Fix `PATH` not being preserved in container shells.
```
Use this for auditing the code changes:
```
tmp=$(mktemp -d -p /tmp)
mkdir -p $tmp/{old,new}
fetchAndCheck() {
    local url=https://github.com/erikarvstedt/extra-container/archive/$1.tar.gz
    curl -sSL $url | tar xz --strip-components=1 -C $2;
    echo "sha256 for $1 is $(nix hash-path --base32 "$2")"
}
fetchAndCheck 0.5 $tmp/old
fetchAndCheck 0.6 $tmp/new
git diff --no-index $tmp/{old,new}
rm -rf $tmp
```

### CODE REVIEW

**Comment by nixbitcoin** [comment]
[Fix for bug I encountered while testing](https://github.com/nixbitcoin/nix-bitcoin/commits/pkgs-updates-nb)

**Comment by erikarvstedt** [comment]
Thanks, I've pulled in your fix.

**Review by nixbitcoin — APPROVED** [review]
ACK a0f48c9de9d2c45e446965bdaf3ad3cf1fc1b90f

Didn't audit code changes thoroughly

**Review by jonasnick — COMMENTED** [review]
ACK a0f48c9de9d2c45e446965bdaf3ad3cf1fc1b90f

**Comment by jonasnick** [comment]
Thanks for the diff script @erikarvstedt

**Pull request merged**
