### PR TITLE
update nixpkgs:

### PR DESCRIPTION
**Pull request by jonasnick**
btcpayserver: 1.11.2 -> 1.11.4
clightning: 23.05.2 -> 23.08.1
hwi: 2.2.1 -> 2.3.1

Remove custom coincurve, since nixos-23.05 includes the latest version of coincurve (18) that's required by pyln-proto.

~~Draft because it'd be better to use cryptography 41 for pyln-proto instead of patching the pyln-proto dependencies.~~

### CODE REVIEW

**Comment by jonasnick** [comment]
Thanks @erikarvstedt for the fixup. Ready for review.

**Comment by erikarvstedt** [comment]
Thanks! [Minor fixup](https://github.com/erikarvstedt/nix-bitcoin/commits/update-nixpkgs53-ea) to simplify the comments.

**Comment by jonasnick** [comment]
`run-tests.sh -s clightning-replication` fails

**Comment by erikarvstedt** [comment]
[fix test `clightning-replication`](https://github.com/erikarvstedt/nix-bitcoin/commits/update-nixpkgs53-ea-2).

**Comment by jonasnick** [comment]
Thanks @erikarvstedt!
Replaced  clightning 23.08 with  23.08.1. The trustedcoin scenario does not appear to succeed.

**Review by erikarvstedt — APPROVED** [review]
ACK c1b370aaa69e82ccc0ca5956f1792f1eec85a7ed

**Pull request merged**
