### PR TITLE
Add --dry-run option to push-release script

### PR DESCRIPTION
**Pull request by jonasnick**
This helped testing #205

### CODE REVIEW

**Comment by jonasnick** [comment]
This has some issues. Marking as WIP

**Comment by jonasnick** [comment]
Issues should be fixed now

**Comment by erikarvstedt** [comment]
Here are some [fixes](https://github.com/erikarvstedt/nix-bitcoin/commits/push-dry-run).

**Comment by jonasnick** [comment]
@erikarvstedt thanks! Squashed your fixes into my branch.

**Review by nixbitcoin — APPROVED** [review]
utACK dd78d2b2a14b033e539862359e8387db6462ad02

**Pull request merged**
