### PR TITLE
Lightning loop

### PR DESCRIPTION
**Pull request by nixbitcoin**
This PR integrates lightning-loop in nix-bitcoin. Lightning Loop is a [Non-Custodial Off/On Chain Bridge](https://github.com/lightninglabs/loop). It can be used for improvised CoinSwaps that utilize the privacy properties of LN.

Details

-  Based on https://github.com/fort-nix/nix-bitcoin/pull/201.
-  For testing purposes it includes https://github.com/NixOS/nixpkgs/pull/89668 in 7d512a5. This can be removed as soon as https://github.com/NixOS/nixpkgs/pull/89668 is merged, and the pinned nixpkgs in 3cbb691 are bumped.
- AFAICT the datadir can't be specified for loopd, but because of `ReadWritePaths` it's created in `/var/lib/lnd/.loopd` with the right permissions, which is kind of what we want.

Tested with a succesful `loop out` tx `f8178663a03d5b492d756f43b9989c1e7f42640b0c837d4957f29080d025d3bd`

### CODE REVIEW

**Comment by nixbitcoin** [comment]
Rebased with upstream lnd

**Comment by sputn1ck** [comment]
I have not looked at the code, but tested a loop in and loop out in my krops setup and it worked great!

**Comment by nixbitcoin** [comment]
Thank you for the blind trust!

**Comment by nixbitcoin** [comment]
Check that lightning-loop fails with the right error, making sure lightning-loop can connect to lnd

**Comment by Kixunil** [comment]
Today I attempted to integrate loop into my deb repository and found out it [doesn't support authentication yet](https://github.com/lightninglabs/loop/issues/194) How did you secure it? Do you rely on namespaces only?

**Comment by nixbitcoin** [comment]
Yes, lightning-loop relies on running inside its own network namespace for security. Only users inside the `nb-lightning-loop` namespace can reach the `loopd` daemon, and only the semi-privileged operator user can place processes into that namespace. Ideally we would get defense-in-depth with authentication. Thank you for linking the issue, we will update lightning-loop as soon as it's closed.

**Pull request merged**
