### PR TITLE
elementsd: replace local version with nixpkgs

### PR DESCRIPTION
**Pull request by prusnak**
After elementsd was added to nixpkgs in https://github.com/NixOS/nixpkgs/pull/130324 we can use version from there

### CODE REVIEW

**Review by jonasnick — COMMENTED** [review]
Hm CI fails with 
```

trying https://github.com/accumulator/charge-lnd/archive/v0.2.1.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   130  100   130    0     0    670      0 --:--:-- --:--:-- --:--:--   670
100 73435    0 73435    0     0   139k      0 --:--:-- --:--:-- --:--:--  139k
unpacking source archive /build/v0.2.1.tar.gz
hash mismatch in fixed-output derivation '/nix/store/5c82y5i0mxm2pg2k3gk3c1ffgmrqv2rv-source':
  wanted: sha256:0l4h3fdvln03ycbg3xngh8vkhgrz4ad864yyn4gmdjp0ypi69qa1
  got:    sha256:0z44q9qr3jw5yb3h2ijrfp8fswvj8b33pgjl9zvbvhgk17hrsr36
cannot build derivation '/nix/store/dczm09ws83fr89gj07bsyplb140wi6a7-charge-lnd-0.2.1.drv': 1 dependencies couldn't be built
```
which I can also reproduce locally. Perhaps it's not in the cache because the build farm couldn't build it either? @mmilata any idea what is going on?

**Comment by mmilata** [comment]
Looks like the hash of the archive changed, perhaps the tag was changed to point to different commit? Upstream already has 0.2.2, I'll bump it in nixpkgs.

**Comment by mmilata** [comment]
NixOS/nixpkgs#130391

**Comment by prusnak** [comment]
> NixOS/nixpkgs#130391

I merged this one to nixpkgs and updated this PR with this merged commit.

**Review by jonasnick — APPROVED** [review]
Thanks @prusnak.

ACK 2f4d7b866c69e0dba6fe2ec4ca09a7c10540bbee

**Review by nixbitcoin — APPROVED** [review]
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

ACK 2f4d7b866c69e0dba6fe2ec4ca09a7c10540bbee
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCgAdFiEEiDOlIkszv4ojhh+OtgROy6La5dAFAmD1S1AACgkQtgROy6La
5dBUtBAAmrm5dKXNJG+l8rgyaT7APss6ri7jS29FgOLQXojJFwgXCM4XHAAU69C4
DrsKQRnYHv7FN7mfKOaD35hxhfhrkU4VYVye6eFxf+VcpUPTOyyHWjTbqha/dST3
GyRl3oXRDS2TnNiwsArp913/IFTgKhYsXpTto6s2MTwalePSHtjgPIKOdHlZMA/s
ER1yl5e4uGsGFkD3ke8picxeTMd7tnZaoH0FD3fMoDyk5BsaBM3SRO26ksJU27D5
cc08VBzBtbDBgbj+Rd1pbAlNyAIddea7aAjvucC13ghV3UfSuDQifSuWLU6MPk4F
PGO2cx/27JONJrkJm8gHMokCLecHagWeN2paIUDFU2QCyS2PYlszz60icmAn9GgM
fcf0x5wwOS+IbnPvPUZQsoEjzxNJrPM9tvFSRC1PDair14ot8QTFzeUBEJVhM2Hx
aZN78poApac4RrPntG4wpUo3AkznnZ3VqoCnhUaZiaz3xJw/fxoXInMTzWV+8JCw
ZLzgSHIxpILUbUY3vy6v1Uk1kfqfaAhCzeXm0Vlf87Pj2Rm0hhF9/sRQGkeEaDSG
KV6kZOroXZ75HVWe9RMWjfXd9Pmm4aYQ8kPH8QIbfXdMn8cb5nLoL3l0nKUP7r0S
bXc0BJU5Z903PsXrX6wTz39eyF7IyDW22HAcii8s+UvSvc/52MY=
=fcwS
-----END PGP SIGNATURE-----
```

**Comment by nixbitcoin** [comment]
In the release notes we should state that the `nixpkgs-unstable` bump also includes electrs 0.8.10, btcpayserver 1.1.2, charge-lnd 0.2.2, and nbxplorer 2.1.52.

**Pull request merged**
