### PR TITLE
joinmarket: 0.8.1 -> 0.8.2

### PR DESCRIPTION
**Pull request by nixbitcoin**
Urgent security update, see [release notes](https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/master/docs/release-notes/release-notes-0.8.2.md)

### CODE REVIEW

**Comment by erikarvstedt** [comment]
Would joinmarket work with the current `cryptography` version from unstable?

**Comment by nixbitcoin** [comment]
> Would joinmarket work with the current `cryptography` version from unstable?

No, its pinned to 3.3.2 because of [this](https://github.com/pyca/cryptography/issues/5771).

**Comment by erikarvstedt** [comment]
Could you add a comment to `python-packages/cryptography/default.nix` to explain why it was copied/pinned?

**Comment by nixbitcoin** [comment]
> Could you add a comment to `python-packages/cryptography/default.nix` to explain why it was copied/pinned?

Sure, but what do you think about patching the pinning out of `joinmarket` and using the newest rust-based version instead?

**Comment by erikarvstedt** [comment]
>  using the newest rust-based version instead
Yeah, great idea!

**Comment by nixbitcoin** [comment]
This is how far I got, I'm having some issues pulling in `cryptography` from unstable (which on our pinned revision is 3.3.2 - so no patch necessary). Maybe you have some ideas.

**Comment by erikarvstedt** [comment]
[Fix](https://github.com/erikarvstedt/nix-bitcoin/commits/joinmarket-0.8.2-ea).
This pins `cryptography` to the exact required version `3.3.2`.

**Comment by erikarvstedt** [comment]
I think my latest fixup is fine (see the updated post).
To use the unstable version, copy the two cryptography sources from unstable and add a `patchPhase` to `nix-bitcoin/pkgs/joinmarket/default.nix` to patch the version in `jmdaemon/setup.py`.

**Comment by nixbitcoin** [comment]
> I think my latest fixup is fine (see the updated post).
> To use the unstable version, copy the two cryptography sources from unstable and add a `patchPhase` to `nix-bitcoin/pkgs/joinmarket/default.nix` to patch the version in `jmdaemon/setup.py`.

Can't we just pull in the `cryptography` version from our pinned nixpkgs-unstable? That would forego adding another package that we need to actively maintain.

**Comment by erikarvstedt** [comment]
No, because `unstable.python3Packages.cryptography` has conflicting python pkg dependencies (`propagatedBuildInputs`). 
We have to evaluate the cryptography derivation in the context of our own Python package set.

**Comment by erikarvstedt** [comment]
We could also track the cryptography version of `pinned.nixpkgs-unstable`. This would avoid copying the sources, 
but the cryptography version may diverge further from the required version in joinmarket on `unstable` updates. This might introduce bugs.
You can implement this approach like this, but using `pinned.nixpkgs-unstable` instead of `nixpkgsCryptography`:
https://github.com/erikarvstedt/nix-bitcoin/commit/a9cd597123820c0352626124220eda0e29d045a0

**Comment by nixbitcoin** [comment]
> You can implement this approach like this, but using `pinned.nixpkgs-unstable` instead of `nixpkgsCryptography`:
> [erikarvstedt@a9cd597](https://github.com/erikarvstedt/nix-bitcoin/commit/a9cd597123820c0352626124220eda0e29d045a0)

Good idea, but I'm getting `error: undefined variable 'pinned'`

**Comment by erikarvstedt** [comment]
`pinned` was just a shorthand to explain the concept.
Use `unstable = (import ../nixpkgs-pinned.nix).nixpkgs-unstable;` and `callPackage "${unstable}/pkgs/development/...`.

**Review by erikarvstedt — APPROVED** [review]
ACK 5ead2a707555d922e0251b2f102dd6df0dab6095

**Pull request merged**
