### PR TITLE
Add Mempool

### PR DESCRIPTION
**Pull request by nixbitcoin**
Closes https://github.com/fort-nix/nix-bitcoin/issues/394

Live at https://mempool.nixbitcoin.org

### CODE REVIEW

**Comment by wiz** [comment]
any ETA to merge this? :)

**Comment by prusnak** [comment]
I see this PR also adds the `fulcrum` (unstable) package. Any reason why not to use the (stable) version of the package [from nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/blockchains/fulcrum/default.nix)?

**Comment by erikarvstedt** [comment]
@prusnak, the newer Fulcrum versions support a much faster initial sync (via option `fast-sync`).

@wiz, Fulcrum `bcccf76`, which was used in this branch, regularly stopped responding to RPC calls after about ~2 weeks of uptime.
I've now [updated Fulcrum](https://github.com/erikarvstedt/nixbitcoin.org/commits/mempool-ea) to the current master (`8acdc92`). Let's see if this works more reliably.

**Comment by cculianu** [comment]
Hi, Fulcrum author here.  @erikarvstedt I'd like more info on your setup and how/why it stops responding to RPC?  I have my server up for 2 months now with ~1000 clients connected... no issues.  Let me know...  (perhaps in the issue on Fulcrum itself).

**Comment by erikarvstedt** [comment]
@cculianu, unfortunately, I didn't investigate these issues as they appeared (although I had planned to do that).
I'm now auto-monitoring our Fulcrum/mempool setup on [nixbitcoin.org](https://mempool.nixbitcoin.org/) and will step in in case another RPC server error happens.

**Comment by prusnak** [comment]
I created PR https://github.com/NixOS/nixpkgs/pull/176545 to update Fulcrum to just released 1.7.0 in nixpkgs. Once that PR is accepted, we can rebase this one to use the package from nixpkgs.

**Comment by wiz** [comment]
fyi we will likely tag mempool v2.4.0 this week

**Comment by erikarvstedt** [comment]
The error just happened again, I just had a quick glance at it.

#### Mempool version
2.3.1

#### Description
Querying any bitcoin address via the webinterface or the API results in error `Connection to server lost, please retry`.
Example:
```
curl http://169.254.1.31:8999/api/v1/address/1CGG9qVq2P6F7fo6sZExvNq99Jv2GDpaLE
#=> Connection to server lost, please retry
```

#### Summary
The bug is in the mempool backend, restarting the backend fixes the bug.
fulcrum is not involved in this bug.

#### Details
Very crudely, I ran
```
mempoolPID=$(systemctl show -p MainPID mempool | cut -d= -f2);
strace -f -p $mempoolPID & pid=$!
curl http://169.254.1.31:8999/api/v1/address/1CGG9qVq2P6F7fo6sZExvNq99Jv2GDpaLE
kill $pid
```
[strace output](https://gist.github.com/8a8175c29655e48099a3b6d2438e053e)
  - `169.254.1.12` is the bitcoind socket address
  - fd `40` is the socket of the client connection
  - During handling the client requirest, the mempool backend doesn't call fulcrum
  
I guess we should update mempool and continue observing this bug.

**Comment by wiz** [comment]
Okay please report it to our Github and we will investigate ASAP

**Comment by erikarvstedt** [comment]
Superseded by #505.

**Pull request closed without merging**
