### PR TITLE
lndconnect: add preconfigured lndconnect-rest script

### PR DESCRIPTION
**Pull request by nixbitcoin**
This PR adds a module that creates an onion service for connecting to the LND REST interface and a preconfigured lndconnect script for automatically printing QR-codes to connect Zeus or Zap. Tested with Zeus.

### CODE REVIEW

**Comment by erikarvstedt** [comment]
[Rewrite](https://github.com/erikarvstedt/nix-bitcoin/commits/lndconnect-ea).
This feature is now a sub-option of `services.lnd`, implemented in an extra file, as before.
I've renamed it to `services.lnd.restOnionService` to emphasize that this exposes lnd's REST service to the public.

**Comment by nixbitcoin** [comment]
I incorporated your changes, but changed the name of the command to `lndconnect-rest-onion` to reflect that this command is specific to the REST interface. We might also want to add `lndconnect-grpc-onion` in the future.

I also added usage instructions for connecting from the Zeus Android App.

**Comment by erikarvstedt** [comment]
[Fixed branch](https://github.com/erikarvstedt/nix-bitcoin/commits/lndconnect-ea-2/) with some formatting fixes.

**Review by erikarvstedt — APPROVED** [review]
ACK 891a69ee8e0ab2826800f0a4e65a94565028630a

**Pull request merged**
