### PR TITLE
Limit syscalls

### LINKED ISSUE #58: Limit syscalls
**Time Horizon:** Short term

**Description:** Limit system calls to further restrict services.

**Motivation:** Continuation of our hardening efforts.

**Implementation:** Use systemd's SYSTEM CALL FILTERING and [Docker's default syscall whitelist](https://raw.githubusercontent.com/docker/docker/master/profiles/seccomp/default.json).

### PR DESCRIPTION
**Pull request by nixbitcoin**
This PR limits syscalls using [Docker's default syscall whitelist](https://raw.githubusercontent.com/docker/docker/master/profiles/seccomp/default.json). Along with the default whitelist it includes amd64, x32, x64, arm and arm64 specific syscalls. It also whitelists the `clone` syscall without which I got an error for every service. We should investigate how the `clone` syscall affects security.

I have also yet to test the syscall whitelist with the bitcoind and clightning test suites.

Closes #58

### CODE REVIEW

**Comment by jonasnick** [comment]
Fwiw if I understand correctly docker's default list allows to call clone with the argument `2080505856` (hex `0x7c020000`), which according to `/usr/src/linux-5.0.10.arch1/include/uapi/linux/sched.h` corresponds to the following flags:
```
CLONE_NEWNS
CLONE_NEWUSER
CLONE_NEWPID
CLONE_NEWNET
CLONE_NEWIPC
CLONE_NEWUTS
```

**Comment by jonasnick** [comment]
You can figure out the syscalls of the python tests by running
```
 PYTHONPATH=contrib/pylightning:$PYTHONPATH TEST_DEBUG=1 DEVELOPER=1 VALGRIND=0 noglob strace -c -f -S name pytest tests/ -v --timeout=550 --timeout_method=thread -p no:logging
```
Note that this also includes syscalls of the python test framework.

**Comment by jonasnick** [comment]
Apparently clone allows to create namespaces. So my understanding is that we can allow it because we have the `RestrictNamespaces=` option set in the default systemd options.

**Comment by nixbitcoin** [comment]
Confirming that `RestrictNamespaces=true` blocks creation of new namespaces. 

Tested using tmux session created with systemd unit file
```
[Unit]
Description=Test Restrictnamespaces=true

[Service]
Type=idle
ExecStart=/usr/bin/tmux new -d -s test
KillMode=process

RestrictNamespaces=true
```
Result:
```
[root@testbitcoin /]# unshare -m
unshare: unshare failed: Operation not permitted
[root@testbitcoin /]# ip netns add test
Failed to create a new network namespace "test": Operation not permitted
```
and tmux session created with systemd unit file
```
[Unit]
Description=Test RestrictNamespaces=true and SystemCallFilter=whitelist

[Service]
Type=idle
ExecStart=/usr/bin/tmux new -d -s test
KillMode=process

RestrictNamespaces=true
SystemCallArchitectures=native
SystemCallFilter=accept accept4 access adjtimex alarm bind brk capget capset chdir chmod chown chown32 clock_getres clock_gettime clock_nanosleep close connect copy_file_range creat dup dup2 dup3 epoll_create epoll_create1 epoll_ctl epoll_ctl_old epoll_pwait epoll_wait epoll_wait_old eventfd eventfd2 execve execveat exit exit_group faccessat fadvise64 fadvise64_64 fallocate fanotify_mark fchdir fchmod fchmodat fchown fchown32 fchownat fcntl fcntl64 fdatasync fgetxattr flistxattr flock fork fremovexattr fsetxattr fstat fstat64 fstatat64 fstatfs fstatfs64 fsync ftruncate ftruncate64 futex futimesat getcpu getcwd getdents getdents64 getegid getegid32 geteuid geteuid32 getgid getgid32 getgroups getgroups32 getitimer getpeername getpgid getpgrp getpid getppid getpriority getrandom getresgid getresgid32 getresuid getresuid32 getrlimit get_robust_list getrusage getsid getsockname getsockopt get_thread_area gettid gettimeofday getuid getuid32 getxattr inotify_add_watch inotify_init inotify_init1 inotify_rm_watch io_cancel ioctl io_destroy io_getevents io_pgetevents ioprio_get ioprio_set io_setup io_submit ipc kill lchown lchown32 lgetxattr link linkat listen listxattr llistxattr _llseek lremovexattr lseek lsetxattr lstat lstat64 madvise memfd_create mincore mkdir mkdirat mknod mknodat mlock mlock2 mlockall mmap mmap2 mprotect mq_getsetattr mq_notify mq_open mq_timedreceive mq_timedsend mq_unlink mremap msgctl msgget msgrcv msgsnd msync munlock munlockall munmap nanosleep newfstatat _newselect open openat pause pipe pipe2 poll ppoll prctl pread64 preadv preadv2 prlimit64 pselect6 pwrite64 pwritev pwritev2 read readahead readlink readlinkat readv recv recvfrom recvmmsg recvmsg remap_file_pages removexattr rename renameat renameat2 restart_syscall rmdir rt_sigaction rt_sigpending rt_sigprocmask rt_sigqueueinfo rt_sigreturn rt_sigsuspend rt_sigtimedwait rt_tgsigqueueinfo sched_getaffinity sched_getattr sched_getparam sched_get_priority_max sched_get_priority_min sched_getscheduler sched_rr_get_interval sched_setaffinity \
                 sched_setattr sched_setparam sched_setscheduler sched_yield seccomp select semctl semget semop semtimedop send sendfile sendfile64 sendmmsg sendmsg sendto setfsgid setfsgid32 setfsuid setfsuid32 setgid setgid32 setgroups setgroups32 setitimer setpgid setpriority setregid setregid32 setresgid setresgid32 setresuid setresuid32 setreuid setreuid32 setrlimit set_robust_list setsid setsockopt set_thread_area set_tid_address setuid setuid32 setxattr shmat shmctl shmdt shmget shutdown sigaltstack signalfd signalfd4 sigreturn socket socketcall socketpair splice stat stat64 statfs statfs64 statx symlink symlinkat sync sync_file_range syncfs sysinfo tee tgkill time timer_create timer_delete timerfd_create timerfd_gettime timerfd_settime timer_getoverrun timer_gettime timer_settime times tkill truncate truncate64 ugetrlimit umask uname unlink unlinkat utime utimensat utimes vfork vmsplice wait4 waitid waitpid write writev arm_fadvise64_64 arm_sync_file_range sync_file_range2 breakpoint cacheflush set_tls arch_prctl modify_ldt s390_pci_mmio_read s390_pci_mmio_write s390_runtime_instr clone
```
Result:
```
[root@testbitcoin /]# unshare -m
Bad system call (core dumped)
[root@testbitcoin /]# ip netns add test
Bad system call (core dumped)
```

**Comment by nixbitcoin** [comment]
All tests passed for bitcoin with

```
test/functional/test_runner.py --extended
```
in tmux session created by
```
[Unit]
Description=Test Bitcoin

[Service]
User=user
Type=idle
ExecStart=/usr/bin/tmux new -d -s test
KillMode=process

RestrictNamespaces=true
SystemCallArchitectures=native
SystemCallFilter=accept accept4 access adjtimex alarm bind brk capget capset chdir chmod chown chown32 clock_getres clock_gettime clock_nanosleep close connect copy_file_range creat dup dup2 dup3 epoll_create epoll_create1 epoll_ctl epoll_ctl_old epoll_pwait epoll_wait epoll_wait_old eventfd eventfd2 execve execveat exit exit_group faccessat fadvise64 fadvise64_64 fallocate fanotify_mark fchdir fchmod fchmodat fchown fchown32 fchownat fcntl fcntl64 fdatasync fgetxattr flistxattr flock fork fremovexattr fsetxattr fstat fstat64 fstatat64 fstatfs fstatfs64 fsync ftruncate ftruncate64 futex futimesat getcpu getcwd getdents getdents64 getegid getegid32 geteuid geteuid32 getgid getgid32 getgroups getgroups32 getitimer getpeername getpgid getpgrp getpid getppid getpriority getrandom getresgid getresgid32 getresuid getresuid32 getrlimit get_robust_list getrusage getsid getsockname getsockopt get_thread_area gettid gettimeofday getuid getuid32 getxattr inotify_add_watch inotify_init inotify_init1 inotify_rm_watch io_cancel ioctl io_destroy io_getevents io_pgetevents ioprio_get ioprio_set io_setup io_submit ipc kill lchown lchown32 lgetxattr link linkat listen listxattr llistxattr _llseek lremovexattr lseek lsetxattr lstat lstat64 madvise memfd_create mincore mkdir mkdirat mknod mknodat mlock mlock2 mlockall mmap mmap2 mprotect mq_getsetattr mq_notify mq_open mq_timedreceive mq_timedsend mq_unlink mremap msgctl msgget msgrcv msgsnd msync munlock munlockall munmap nanosleep newfstatat _newselect open openat pause pipe pipe2 poll ppoll prctl pread64 preadv preadv2 prlimit64 pselect6 pwrite64 pwritev pwritev2 read readahead readlink readlinkat readv recv recvfrom recvmmsg recvmsg remap_file_pages removexattr rename renameat renameat2 restart_syscall rmdir rt_sigaction rt_sigpending rt_sigprocmask rt_sigqueueinfo rt_sigreturn rt_sigsuspend rt_sigtimedwait rt_tgsigqueueinfo sched_getaffinity sched_getattr sched_getparam sched_get_priority_max sched_get_priority_min sched_getscheduler sched_rr_get_interval sched_setaffinity \
                 sched_setattr sched_setparam sched_setscheduler sched_yield seccomp select semctl semget semop semtimedop send sendfile sendfile64 sendmmsg sendmsg sendto setfsgid setfsgid32 setfsuid setfsuid32 setgid setgid32 setgroups setgroups32 setitimer setpgid setpriority setregid setregid32 setresgid setresgid32 setresuid setresuid32 setreuid setreuid32 setrlimit set_robust_list setsid setsockopt set_thread_area set_tid_address setuid setuid32 setxattr shmat shmctl shmdt shmget shutdown sigaltstack signalfd signalfd4 sigreturn socket socketcall socketpair splice stat stat64 statfs statfs64 statx symlink symlinkat sync sync_file_range syncfs sysinfo tee tgkill time timer_create timer_delete timerfd_create timerfd_gettime timerfd_settime timer_getoverrun timer_gettime timer_settime times tkill truncate truncate64 ugetrlimit umask uname unlink unlinkat utime utimensat utimes vfork vmsplice wait4 waitid waitpid write writev arm_fadvise64_64 arm_sync_file_range sync_file_range2 breakpoint cacheflush set_tls arch_prctl modify_ldt clone
```

**Comment by nixbitcoin** [comment]
All tests except `test_bech32_funding`  passed for clightning with
```
PYTHONPATH=contrib/pylightning:$PYTHONPATH TEST_DEBUG=1 DEVELOPER=1 VALGRIND=0 pytest tests/ -v --timeout=550 --timeout_method=thread -p no:logging
```
in tmux session created by
```
[Unit]
Description=Test clightning

[Service]
Type=idle
ExecStart=/usr/bin/tmux new -d -s test
KillMode=process
User=user

RestrictNamespaces=true
SystemCallArchitectures=native
SystemCallFilter=accept accept4 access adjtimex alarm bind brk capget capset chdir chmod chown chown32 clock_getres clock_gettime clock_nanosleep close connect copy_file_range creat dup dup2 dup3 epoll_create epoll_create1 epoll_ctl epoll_ctl_old epoll_pwait epoll_wait epoll_wait_old eventfd eventfd2 execve execveat exit exit_group faccessat fadvise64 fadvise64_64 fallocate fanotify_mark fchdir fchmod fchmodat fchown fchown32 fchownat fcntl fcntl64 fdatasync fgetxattr flistxattr flock fork fremovexattr fsetxattr fstat fstat64 fstatat64 fstatfs fstatfs64 fsync ftruncate ftruncate64 futex futimesat getcpu getcwd getdents getdents64 getegid getegid32 geteuid geteuid32 getgid getgid32 getgroups getgroups32 getitimer getpeername getpgid getpgrp getpid getppid getpriority getrandom getresgid getresgid32 getresuid getresuid32 getrlimit get_robust_list getrusage getsid getsockname getsockopt get_thread_area gettid gettimeofday getuid getuid32 getxattr inotify_add_watch inotify_init inotify_init1 inotify_rm_watch io_cancel ioctl io_destroy io_getevents io_pgetevents ioprio_get ioprio_set io_setup io_submit ipc kill lchown lchown32 lgetxattr link linkat listen listxattr llistxattr _llseek lremovexattr lseek lsetxattr lstat lstat64 madvise memfd_create mincore mkdir mkdirat mknod mknodat mlock mlock2 mlockall mmap mmap2 mprotect mq_getsetattr mq_notify mq_open mq_timedreceive mq_timedsend mq_unlink mremap msgctl msgget msgrcv msgsnd msync munlock munlockall munmap nanosleep newfstatat _newselect open openat pause pipe pipe2 poll ppoll prctl pread64 preadv preadv2 prlimit64 pselect6 pwrite64 pwritev pwritev2 read readahead readlink readlinkat readv recv recvfrom recvmmsg recvmsg remap_file_pages removexattr rename renameat renameat2 restart_syscall rmdir rt_sigaction rt_sigpending rt_sigprocmask rt_sigqueueinfo rt_sigreturn rt_sigsuspend rt_sigtimedwait rt_tgsigqueueinfo sched_getaffinity sched_getattr sched_getparam sched_get_priority_max sched_get_priority_min sched_getscheduler sched_rr_get_interval sched_setaffinity \
                 sched_setattr sched_setparam sched_setscheduler sched_yield seccomp select semctl semget semop semtimedop send sendfile sendfile64 sendmmsg sendmsg sendto setfsgid setfsgid32 setfsuid setfsuid32 setgid setgid32 setgroups setgroups32 setitimer setpgid setpriority setregid setregid32 setresgid setresgid32 setresuid setresuid32 setreuid setreuid32 setrlimit set_robust_list setsid setsockopt set_thread_area set_tid_address setuid setuid32 setxattr shmat shmctl shmdt shmget shutdown sigaltstack signalfd signalfd4 sigreturn socket socketcall socketpair splice stat stat64 statfs statfs64 statx symlink symlinkat sync sync_file_range syncfs sysinfo tee tgkill time timer_create timer_delete timerfd_create timerfd_gettime timerfd_settime timer_getoverrun timer_gettime timer_settime times tkill truncate truncate64 ugetrlimit umask uname unlink unlinkat utime utimensat utimes vfork vmsplice wait4 waitid waitpid write writev arm_fadvise64_64 arm_sync_file_range sync_file_range2 breakpoint cacheflush set_tls arch_prctl modify_ldt clone
```
`test_bech32_funding` fails inside and outside of tmux with 
```
E           bitcoin.rpc.InvalidAddressOrKeyError: {'code': -5, 'message': 'No such mempool transaction. Use -txindex to enable blockchain transaction queries. Use gettransaction for wallet transactions.'}
```
seems to be unrelated.

**Comment by nixbitcoin** [comment]
Rebased and ready to merge.

**Comment by jonasnick** [comment]
I can't reproduce the bech32 test failure.
Which clightning and bitcoind version did you use?

**Comment by nixbitcoin** [comment]
clightning v0.7.0 (commit 4a11bc07f9bc474cbe5eb6f9e45c71075d40fda3) and bitcoin v0.18.0 (commit 2472733a24a9364e4c6233ccd04166a26a68cc65) on both Fedora 29 and Debian Stretch.

**Comment by jonasnick** [comment]
I ran the steps you showed here but included the already existing service hardening measures and was able to verify that bitcoind and lightning tests pass and the bech32 failure happens both with and without the containerized tmux.

**Pull request merged**
