### PR TITLE
ShellCheck on scripts generated by nix

### LINKED ISSUE #528: ShellCheck - lint for shell scripts
Many shell scripts in nix-bitcoin project do not pass the shellcheck lint. I think it's good idea to at least prevent the potential globbing and word splitting.

We can integrate the changes carefully and slowly.

I would like to divide the work into these parts:

1. Fix the lint of shell scripts installed on a target machine - mainly scripts called by unit files (`ExecStart(Post|Pre)`) and scripts used in packages (`postInstall`, `buildCommand`, ...)
2. Add tests which automatically check the lint of these scripts in CI
3. Fix the lint of other shell scripts (various helper scripts in this repository). We can also add automatic shellcheck test for these scripts to CI.

The draft PR of proposed changes (points 1. and 2.) will follow. Please let me know what you think.

Refs.:
- https://www.shellcheck.net/wiki/

Thanks!

cc: @erikarvstedt 

### TODOs:
- [ ] https://github.com/NixOS/nixpkgs/pull/189836
- [ ] https://github.com/fort-nix/nix-bitcoin/pull/529
- [x] https://github.com/fort-nix/nix-bitcoin/pull/531

### PR DESCRIPTION
**Pull request by seberm**
- Fixes #528 
- https://github.com/NixOS/nixpkgs/pull/189836

### CODE REVIEW

**Comment by seberm** [comment]
Hello @erikarvstedt @jonasnick,
what do you think about the changes? Could you please help me, with the review?

Thanks!

**Comment by jonasnick** [comment]
Thanks for your PR @seberm. But I'm sorry, I can't promise a review.

**Comment by erikarvstedt** [comment]
@seberm, thanks, I'll tackle this today.

**Comment by erikarvstedt** [comment]
[Fixed branch](https://github.com/erikarvstedt/nix-bitcoin/commits/feature/shellcheck-on-generated-scripts-ea):
- Rebased to #547
- Move the service shellcheck from the VM test to a dedicated derivation.
  Advantages:
  - All services defined by nix-bitcoin are auto detected.
    This simplifies maintenance. Also, this uncovered a few more non-critical issues.
  - The test builds much faster because no VM has to be started.
- Scripts in `ExecStop` are now checked.

**Comment by seberm** [comment]
Hello @erikarvstedt,
thanks for your changes and the review! I have rebased your changes onto my feature branch.

**Review by erikarvstedt — APPROVED** [review]
ACK 386cb08b42a8c709eee563fa8f7f4c61a98aca06

**Review by erikarvstedt — CHANGES_REQUESTED** [review]
[Fixed branch](https://github.com/erikarvstedt/nix-bitcoin/commits/feature/shellcheck-on-generated-scripts-ea).

This provides the shellcheck derivation as a NixOS module for simpler and more versatile usage.
The shellcheck test is now automatically run as part of every VM test build.

**Review by jonasnick — COMMENTED** [review]
I had a look at @erikarvstedt's branch but I'm missing something. How do I get shellcheckServices to error out? I tried to remove a few quotes from the joinmarket module that were added in this PR and ran the tests. I can see the shellcheckServices output in the logs but no error.

**Comment by erikarvstedt** [comment]
Can you share an example? After adding an offending expression to `systemd.services.joinmarket.postStart`, it is correctly detected with `run-tests.sh`.

**Comment by jonasnick** [comment]
https://github.com/jonasnick/nix-bitcoin/commits/feature/shellcheck-on-generated-scripts-jn

**Comment by erikarvstedt** [comment]
The first hunk affects the builder of `joinmarket.cli`, which was never checked (like the `cli` script itself).
The issue with the second hunk can't be detected by shellcheck because the expansion of `dataDir` happens during nix evaluation.

**Comment by erikarvstedt** [comment]
The cli scripts are mostly trivial oneliners, I'm not sure if it's worth to add shellcheck support for them.

**Comment by jonasnick** [comment]
Ok I see. I didn't expect shell fixes in this PR that are not tested.

**Comment by jonasnick** [comment]
Concept ACK erikarvstedt's branch

**Review by erikarvstedt — APPROVED** [review]
ACK f3f8d650ab1e588fa6ad3041757493e84be4809c

**Review by jonasnick — APPROVED** [review]
Concept ACK f3f8d650ab1e588fa6ad3041757493e84be4809c

**Pull request merged**
