### PR TITLE
Fix process info restriction

### PR DESCRIPTION
**Pull request by erikarvstedt**
@nixbitcoin, please keep in mind that nix-bitcoin supports
just importing modules.nix, without using the secure-node preset.
You broke that at a few places, some are fixed here.

### CODE REVIEW

**Review by jonasnick — COMMENTED** [review]
concept ACK. How was importing just module.nix broken? Can we add a CI test for this?

**Comment by erikarvstedt** [comment]
The whole config was automatically enabled when including the modules. Besides changing `/proc` access, this broke `systemctl status` for non-root users.

Fixed [in this commit](https://github.com/fort-nix/nix-bitcoin/pull/225/commits/44de5064cd9f8ae625997955820146b38afedf90).

**Comment by erikarvstedt** [comment]
Yes, adding another VM test is simple, but it takes a large toll on the total test duration. Keeping this low is crucial for a good dev experience. I'll think about how to best solve this, maybe just evaling a config is enough.

**Comment by erikarvstedt** [comment]
Edit: Note that in this specific case, a "modules-only" test case most likely wouldn't have caught the bug.

**Review by nixbitcoin — APPROVED** [review]
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

ACK 44de5064cd9f8ae625997955820146b38afedf90
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCgAdFiEEV3o0Un8+KoXoD+Fk3RH5rVMIs7oFAl9D0A0ACgkQ3RH5rVMI
s7o7kxAAmWnS3QFixw62xpPXx9WHa4zcok/qddXVH+7m0hftX/ucOvaPdkrbkWx3
sH5HxyCzngbCfGTrrr6XSbMHhmuC1kvgrvsvXPm0T3x5rS43KnakbW94Ts10LXFx
bA0tUaQRJc3PKwtumD8FbOM+irzf7VwX5ygpbNQrukWdLwn4JFDwk0H9Z6cRfcJ3
dvcdhdKOfL1j2gt0G8ak90l0BwsGxi47GcNxOz0QwrQe/7BBQJx3O2oUkpD7gt8Y
EuiCT/sqd0qCUhjgqGq2yAaERCSdtqf/y54ZxUA2hRKtQrcbc+zQ29upsOgY1Y/F
Hxv2OWV9phyd9oltoipF6dfQQ+9o/u9rctnV6qqxOMGK7iNgcEd35OdZNkI1cS26
4iZ6Aw6Vt2X+ibMwXjxTmBU8v/PRfTRNQSh+yFpV7FlqHVjuaElxREfuvsZD8tRf
WWDbE7Q6ecWONEdKH49yKOaYI89FoA8BQEo6YrcKp3epl810TcUxyKDuKSie4eSz
QmlKEpjQriU80LvE0x2zJyJOxxda6a7S1utwRTtt6PgOoAugCwlDuxxa0kjF+619
6sHoJ2z115IBIwt1vxup+519Trvh/tt8evrgAMzPrx9CLVNlxLjd/sBXQ++uI1jp
nt1qgBOI7MdsZ1MXDrKbaiwG1CpYnm0xg99W/LAufhWTYd/zykQ=
=VG5g
-----END PGP SIGNATURE-----
```

**Pull request merged**
