### PR TITLE
Add nix-bitcoin.lib for utility functions and types

### PR DESCRIPTION
**Pull request by jonasnick**

### CODE REVIEW

**Comment by erikarvstedt** [comment]
Good idea. [Fixes.](https://github.com/erikarvstedt/nix-bitcoin/commits/lib-ea)

**Comment by jonasnick** [comment]
Thanks. Cherry-picked and squashed

**Comment by erikarvstedt** [comment]
You accidentally pulled in PR https://github.com/fort-nix/nix-bitcoin/pull/206. :cat:
Besides that, ACK!

**Review by erikarvstedt — APPROVED** [review]

**Comment by erikarvstedt** [comment]
ACK 322ba5bfff1dc250b28ee6ccffa33316fbf334ce

**Comment by nixbitcoin** [comment]
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

ACK 322ba5bfff1dc250b28ee6ccffa33316fbf334ce
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCgAdFiEEV3o0Un8+KoXoD+Fk3RH5rVMIs7oFAl9DnXYACgkQ3RH5rVMI
s7ppog//ap3n3tW6Xq7JKvh1QkovNoMUjxQJpLDnLF04ncUSamqmH11MwekrEVwy
6/GUBQvjLNdRqweiTRX0HV9ylBveqC4R4yngPDS0JSZ8NkLpqwcqCWRTWwl+00Ut
2TpJ5k5Fuuw5Pzs4pwU9TnZEa8qG7TyjXLnU+6SNs3EbKEsV6i4ipS6m6FqG7fln
9RaKyj2ToCxKyAhwybW9XBIhHCCQ5I8k48rV/ZnnLKAE4EskWJXAsCdpj5Yfp1BH
vMLGEswoPCnK40fs9KLAuu7e4fQ+M7YCxXoWaDMl7WTCC0awte+qid4vsBVlRteq
cpSA7Rtbx9Y/xszBB9EhKIALQ0ZN/eBsvKujbAwVIHnqT1iXunbl3jQT/hSUgTX1
Gst+Avtw1LT8BhdGgNjOwmWRYlrnfXjvTpwv6yedJ0O5kfKo5jPGKvxNot3C3M8c
FDyy9inJlD+7VDMTF7jOTh4vheZPEQTkU9UArVN8h8i+OmkvUdDqJ/nv+Uf15RMm
8UxoJ23Vk2nTiQDO3+jTMAWheXtV4/ifhFb15KTa6RXqgub1S8uk9XetZgFusQO1
Bs3hu8Kde0zxI0ETKcYKAbvNqZ+eqpe+3/Zi8HejVKLAgkomLvX04oFAw+iILrjY
ccUUHGM1rrauzBygWcsyrttEWw/haNr63mEpDv70p2po1bEwClc=
=jtmn
-----END PGP SIGNATURE-----
```

**Pull request merged**
