### PR TITLE
Update nixpkgs

### PR DESCRIPTION
**Pull request by jonasnick**
Based on #363 but with the improvements mentioned [here](https://github.com/fort-nix/nix-bitcoin/pull/363#pullrequestreview-692235135). Also bumps the nixpkgs yet again.

CC @mmilata

### CODE REVIEW

**Review by mmilata — DISMISSED** [review]
LGTM, did not test, thanks for fixing my PR!

**Comment by nixbitcoin** [comment]
lnd is failing with

```
Jul 08 10:25:23 nix-bitcoin systemd[1]: Starting lnd.service...
Jul 08 10:25:27 nix-bitcoin lnd[4508]: 2021-07-08 10:25:27.223 [INF] LTND: Version: 0.13.0-beta commit=, build=production, logging=default, debuglevel=info
Jul 08 10:25:27 nix-bitcoin lnd[4508]: 2021-07-08 10:25:27.224 [INF] LTND: Active chain: Bitcoin (network=mainnet)
Jul 08 10:25:27 nix-bitcoin lnd[4508]: 2021-07-08 10:25:27.559 [INF] RPCS: RPC server listening on 169.254.1.14:10009
Jul 08 10:25:27 nix-bitcoin fdnnkvasfq0l0ivi5qm804fh7w5cy68r-lnd-create-wallet[4509]: Unlock lnd wallet
Jul 08 10:25:27 nix-bitcoin lnd[4508]: 2021-07-08 10:25:27.768 [INF] RPCS: gRPC proxy started at 169.254.1.14:8080
Jul 08 10:25:27 nix-bitcoin lnd[4508]: 2021/07/08 10:25:27 http: TLS handshake error from 169.254.1.14:59092: EOF
Jul 08 10:25:27 nix-bitcoin lnd[4508]: 2021-07-08 10:25:27.896 [INF] LTND: Opening the main database, this might take a few minutes...
Jul 08 10:25:27 nix-bitcoin lnd[4508]: 2021-07-08 10:25:27.908 [INF] LTND: Opening bbolt database, sync_freelist=false, auto_compact=false
Jul 08 10:25:28 nix-bitcoin lnd[4508]: 2021-07-08 10:25:28.237 [ERR] RPCS: [/lnrpc.WalletUnlocker/UnlockWallet]: waiting to start, RPC services not available
Jul 08 10:25:47 nix-bitcoin lnd[4508]: 2021-07-08 10:25:47.045 [INF] CHDB: Checking for schema update: latest_version=22, db_version=22
Jul 08 10:25:47 nix-bitcoin lnd[4508]: 2021-07-08 10:25:47.046 [INF] LTND: Database now open (time_to_open=19.137297482s)!
Jul 08 10:25:47 nix-bitcoin lnd[4508]: 2021-07-08 10:25:47.047 [INF] LTND: Waiting for wallet encryption password. Use `lncli create` to create a wallet, `lncli unlock` to unlock an existing wallet, or `lncli changepassword` to change the password of an existing wallet and unlock it.
Jul 08 10:26:54 nix-bitcoin systemd[1]: lnd.service: start-post operation timed out. Terminating.
Jul 08 10:26:54 nix-bitcoin fdnnkvasfq0l0ivi5qm804fh7w5cy68r-lnd-create-wallet[4690]: {"error":"waiting to start, RPC services not available","code":2,"message":"waiting to start, RPC services not available","details":[]}
Jul 08 10:26:54 nix-bitcoin systemd[1]: lnd.service: Control process exited, code=killed, status=15/TERM
Jul 08 10:26:54 nix-bitcoin lnd[4508]: 2021-07-08 10:26:54.502 [INF] LTND: Received terminated
Jul 08 10:26:54 nix-bitcoin lnd[4508]: 2021-07-08 10:26:54.504 [INF] LTND: Shutting down...
Jul 08 10:26:54 nix-bitcoin lnd[4508]: 2021-07-08 10:26:54.504 [INF] LTND: Gracefully shutting down.
Jul 08 10:26:54 nix-bitcoin lnd[4508]: 2021-07-08 10:26:54.506 [ERR] LTND: unable to set up wallet password listeners: shutting down
Jul 08 10:26:54 nix-bitcoin lnd[4508]: 2021-07-08 10:26:54.562 [INF] LTND: Shutdown complete
Jul 08 10:26:54 nix-bitcoin lnd[4508]: unable to set up wallet password listeners: shutting down
Jul 08 10:26:54 nix-bitcoin systemd[1]: lnd.service: Main process exited, code=exited, status=1/FAILURE
Jul 08 10:26:54 nix-bitcoin systemd[1]: lnd.service: Failed with result 'timeout'.
Jul 08 10:26:54 nix-bitcoin systemd[1]: Stopped lnd.service.
```

**Comment by jonasnick** [comment]
@nixbitcoin I cannot reproduce this. It works fine with `./run-tests.sh -s lnd vm`. I added a `--retry` argument to curl. Does that work for you?

**Comment by nixbitcoin** [comment]
That fixed the issue for me. How did you choose the 10 retry value?

**Comment by mmilata** [comment]
Did not really think about the value very much. Probably better to make this higher to give slower hardware a chance - do we gain anything by making it lower?

https://curl.se/docs/manpage.html#--retry

**Review by nixbitcoin — APPROVED** [review]
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

ACK ce10003747c77e8f075359fe82ca6d0a435ff90c
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCgAdFiEEiDOlIkszv4ojhh+OtgROy6La5dAFAmDoPMgACgkQtgROy6La
5dAClQ//fUfNrYFkkhUrjL5b0dRn9xJjC6HjKOlBmHGYqAd1f755R53thaVImVIp
6uZZkK82HGGC7J4dbSDEGZr0Uf/+zTzSjp04ITKX4gp2uY26SgDCLgA4hNQ3ku+2
+0rfpxxztzPmWaiMSWbDIll7MuQPhpCHoHy+Ou3wSISaMRMfW73yG/vvnWhM0PfB
LVGTWmv+wVnOu7Hduu5/sEk0a5wIHN3zW3CagX/JE+mQjUnqCXNButfPro8KrOUo
iW7kkLju419em5lzop8WJ1RhWp/XGIkD0aQOf6hBv36O7RuDMRyI7PUec//anOMK
sv9mX5HM3JYKc0NB2z1+AGC9WRnuE4UfEXKeWVyc36KEpdP1yDdKDkCBNzIEOG97
mFq1ZjsfU5xJmCaubmg+Dbh+2Sygrwtqifa4FOeSQe3GLWMLLjqKc3usYlsRyXI4
T0op/9G8Q37BUkRMdF5tJz1JIiQ7FgNkJlXn5g9OzXui6ZNqOBPLD/zkCxAkBq9e
YxGMZ7vtl/7BQrmodHIBwk9b+H4jEFN04CWIoe+kjhYCjzaFRbjKg3UOcy/vngJM
sChsuy7n6U5RCars4glXbC9cAoOLVFnMgya8fDPkSV2UmHps3mjCKA3EoLJgKZfG
FuTGE3sO67n2OyeYJNy15IhZarUggJebU4vyaZa384St8TAqVFo=
=y7oS
-----END PGP SIGNATURE-----
```

**Pull request merged**
