### PR TITLE
update nixpkgs

### PR DESCRIPTION
**Pull request by jonasnick**
bitcoin: 27.1 -> 28.0
bitcoind: 27.1 -> 28.0
clboss: 0.13.3 -> 0.14.0

### CODE REVIEW

**Review by 0xB10C — APPROVED** [review]
ACK 967e170682afbde62fa020a84f50e8137e45bb29. The updates and LND config change seem reasonable to me.

**Review by erikarvstedt — CHANGES_REQUESTED** [review]
I did review this PR right after it was created. I noticed that test `trustedcoin` is consistently failing due to a timeout at this step:
```
machine: waiting for success: journalctl -b --output=cat -u clightning --grep='plugin-trustedcoin[^^]\[0m\s+bitcoind RPC working'
```
Will look into this soon.

**Comment by jonasnick** [comment]
Oh, thanks @erikarvstedt. Good catch.

**Comment by VzxPLnHqr** [comment]
So far using bitcoind v28.0 and LND via this PR branch has given me no issues.

**Comment by erikarvstedt** [comment]
Blocked by https://github.com/nbd-wtf/trustedcoin/issues/33

**Comment by erikarvstedt** [comment]
[Fixed branch](https://github.com/erikarvstedt/nix-bitcoin/commits/update-nixpkgs69-ea) with trustedcoin update.

**Comment by jonasnick** [comment]
@erikarvstedt Thanks! The trustedcoin test still fails for me due a time out at
```
vm-test-run-nix-bitcoin-trustedcoin> machine: waiting for success: journalctl -b --output=cat -u clightning --grep='plugin-trustedcoin[^^]\[0m\s+estimatefees error: none of the esploras returned usable responses'
```

**Comment by erikarvstedt** [comment]
Thanks, fixed my branch.

**Comment by jonasnick** [comment]
@erikarvstedt Thanks. Updated the PR.

**Review by erikarvstedt — APPROVED** [review]
ACK 2f986c80e5d7950ef7f0cd14f672e82b5fe2027c

**Pull request merged**
