### PR TITLE
joinmarket: include the bond-calculator script

### LINKED ISSUE #693: Add bond-calculator.py to the JoinMarket cli tools
It would be nice to be able to use the bond calculator script easily with Nix-Bitcoin for JoinMarket makers.

I was thinking the script `jm-bond-calculator` could be the command.

Here is more information on the script and the reason for it. https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/master/docs/fidelity-bonds.md#what-amount-of-bitcoins-to-lock-up-and-for-how-long

### PR DESCRIPTION
**Pull request by seberm**
Closes #693 

Include the [bond-calculator.py](https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/master/scripts/bond-calculator.py) script into joinmarket's CLI commands.

### CODE REVIEW

**Review by jonasnick — COMMENTED** [review]
Concept ACK

**Review by erikarvstedt — APPROVED** [review]
ACK d1eb9778d165705e8a63bd89c804d2a2c73c837b

**Comment by seberm** [comment]
I can include these changes as a part of !702 or you can merge it and I will rebase my changes. The choice is yours. Thanks!

**Comment by jonasnick** [comment]
Merged this first because it had already been approved.

**Pull request merged**
