### PR TITLE
update nixpkgs

### PR DESCRIPTION
**Pull request by jonasnick**

### CODE REVIEW

**Comment by nixbitcoin** [comment]
[Fixup with JoinMarket patch](https://github.com/nixbitcoin/nix-bitcoin/tree/update-nixpkgs20-nb)

**Comment by jonasnick** [comment]
bumped nixpkgs

**Comment by jonasnick** [comment]
Cherry picked. Thanks @nixbitcoin

**Comment by erikarvstedt** [comment]
We should wait for the next `nixpkgs-unstable` [channel update](https://status.nixos.org/) which will include the latest `btcpayserver` release.

**Review by nixbitcoin — APPROVED** [review]
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

ACK 23935ade9174185408b3e245a82908387249a1b0
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCgAdFiEEiDOlIkszv4ojhh+OtgROy6La5dAFAmE+CkUACgkQtgROy6La
5dD4wQ/+NLedYvWxsDUWyWMV9bTflz+kzfRttTpVHAlCqKkn2BlNc3XiDNDYIU98
X15NXDvYnGm4g0bTF7cGnnWMMw2KCMUcn8RYa32ZbjiPp7dDN7JNliGWVhFAvR11
oxq8UjpIKIFa8v5e6eZHecI6hPL49hLL5+bA/9+7u0G7u/dqhOl5AF5+SGYzl92u
aYDrGsl3zbydUdNqfD6oNLh8PlL1n3vujjDWj/SP9orRirSVtqggBa+j1koKYrxF
HEmQO3FIG/Cjviar5sKpdCV19HQPU8J2veyJX5p2e2GadypEeMsXoFlyy1qfKef8
xPY9Nc+/kSAtV1yN/Oh3Dv7R1gg6BijzmFel0IH4XU/aYx9YzbCl4iC4p+i4W/qf
4xzTzPUIJMb1hve30x4BpsJa0/8HaeIRLDFlLp9w9p7Wbxi/Cs2rF6dW5wxBTeNy
vEw4QBAiX+ecUR3OwplFirtyq+LIYhKiL7qLk5sYGQDO+nSf1hyXqK9bslTrYV8b
hHeB5sxmkjlstzmvr7DfH5CxDOQ3fRy+8KcqkO9gFJhH60zd/ZuQbuEeWzVuCcA/
hbtFR3MstbMISVwBECTOqfSrbkmlyIT7P/XLYg/b2ndtbvyLOw2MNZwo6dTm0t71
ROIRXQ+pSEHeKZCTurtixl+l0isnCBr4p0AsdyydVbZAZ4hUyi0=
=Yqjn
-----END PGP SIGNATURE-----
```

**Comment by jonasnick** [comment]
rebased

**Comment by jonasnick** [comment]
Ok we can wait for btcpayserver.

**Review by erikarvstedt — APPROVED** [review]
ACK 3e146512d7b1690277e23fe516dede8025d8dd8c

**Pull request merged**
