### PR TITLE
joinmarket 0.7.0 -> 0.7.2 & lightning-loop 0.10.0-beta -> 0.11.0-beta

### PR DESCRIPTION
**Pull request by nixbitcoin**
joinmarket 0.7.0 -> 0.7.2 & lightning-loop 0.10.0-beta -> 0.11.0-beta pkg updates with associated module changes.

### CODE REVIEW

**Review by erikarvstedt — CHANGES_REQUESTED** [review]
[Minor fixup](https://github.com/erikarvstedt/nix-bitcoin/commits/pkg-updates2-ea).

**Comment by nixbitcoin** [comment]
Fixup merged

**Review by erikarvstedt — DISMISSED** [review]
ACK b96f21ae329ba3e9969edd94590f149c1877b274

**Comment by jonasnick** [comment]
CI failed

**Comment by erikarvstedt** [comment]
The failure happened when `netns-bitcoind` was restarted.
```
machine # [  282.315628] systemd[1]: Starting netns-bitcoind.service...
machine # [  282.395100] alpmqly8gdkff6hs8dpjpab24x8fi119-unit-script-netns-bitcoind-start[19978]: RTNETLINK answers: File exists
machine # [  282.444695] systemd[1]: netns-bitcoind.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

I can't repro this error locally. It was probably introduced by my last PR and is related to `ip netns`'s async mode of operation, where its effects are not immediately visible when the comand exits. The slower CI nodes expose such timing bugs.

The log error `RTNETLINK answers: File exists` points to line `${ipNetns} addr add ${v.address}/24 dev ${veth}` in the netns setup script.
To clarify this, I've [added a debug helper](https://github.com/erikarvstedt/nix-bitcoin/commit/736b572d41fcc0ca7b2dcfb83c1d6b6bf4d63c94) and re-run the [travis build](https://travis-ci.org/github/erikarvstedt/nix-bitcoin/builds/741098187), but it's still stalling, like in the last few days.
@jonasnick, should I investigate a migration to Github Actions?

**Comment by jonasnick** [comment]
@nixbitcoin can you rebase? That'll probably fix CI.

**Comment by nixbitcoin** [comment]
Rebased

**Review by erikarvstedt — APPROVED** [review]
ACK 546053511b041e401c09ea647d29cff95fa17ae3

**Comment by jonasnick** [comment]
restarted that job just to give it another try

**Comment by jonasnick** [comment]
worked this time

**Pull request merged**
