### PR TITLE
charge-lnd: add module

### PR DESCRIPTION
**Pull request by mmilata**
Adds module for [charge-lnd](https://github.com/accumulator/charge-lnd), a tool for updating lnd channel fees based on list of rules.

~~The package is temporarily included for ease of testing as it has been submitted to nixpkgs unstable https://github.com/NixOS/nixpkgs/pull/124436. Marking this as a draft until then, early feedback appreciated though.~~

TODO:
- [ ] ~~validate config file using `charge-lnd --dry-run` at build time like e.g. nginx does~~

### CODE REVIEW

**Comment by erikarvstedt** [comment]
[Fixups](https://github.com/erikarvstedt/nix-bitcoin/commits/charge-lnd-ea).
I've set the service type to `oneshot` to simplify the test. This setting is only appropriate for very short-running services. Does this apply to `charge-lnd`?
What's the rationale for `RandomizedDelaySec` in the timer?

**Comment by mmilata** [comment]
Thanks for the fixups! I'm a bit torn regarding the type of `policies` option, seems like NixOS tends to prefer structured config whenever possible([1](https://github.com/NixOS/rfcs/blob/master/rfcs/0042-config-option.md),[2](https://nixos.org/manual/nixos/stable/index.html#sec-freeform-modules)) though you're right there's not much validation going on.

Btw my intention was to wait until the package is accepted to nixpkgs, and nix-bitcoin updates the pinned nixpkgs version. I don't mind it living in this repo, however it probably doesn't make sense to maintain it in both places long-term.

> I've set the service type to oneshot to simplify the test. This setting is only appropriate for very short-running services. Does this apply to charge-lnd?

Yes, it only runs couple of seconds, oneshot seems the most appropriate type.

> What's the rationale for RandomizedDelaySec in the timer?

To avoid scenarios where nix-bitcoin and this module become very popular and thousands of nodes will be changing the fees at the same time causing gossip spikes or other weird effects. Far fetched, yes. We can probably live without this option.

**Comment by mmilata** [comment]
Build-time syntax check requires code changes, postponing it until accumulator/charge-lnd#26 is merged/rejected.

**Comment by erikarvstedt** [comment]
> To avoid scenarios where nix-bitcoin and this module become very popular

Agreed, good point.
You can squash the fixups if you like.

**Comment by erikarvstedt** [comment]
The CI test failed with a concurrency error in `charge-lnd` ([full log](https://api.cirrus-ci.com/v1/task/4879528074936320/logs/build.log)).
```
machine # [  108.767869] systemd[1]: Starting charge-lnd.service...
machine # [  127.533926] charge-lnd[18380]: E0604 19:06:39.360506103   18481 sync_posix.cc:67]           assertion failed: pthread_mutex_lock(mu) == 0
...
machine # [1]: charge-lnd.service: Main process exited, code=killed, status=6/ABRT
machine # [  129.226415] systemd[1]: charge-lnd.service: Failed with result 'signal'.
```
This didn't happen locally for me yet.
Maybe you could raise this issue upstream.

**Comment by mmilata** [comment]
Fits grpc/grpc#24921, unfortunately there's no info on what's wrong or how to fix it. Can you please rerun the test to see if it's reproducible?

**Comment by erikarvstedt** [comment]
Here's the [successful re-run](https://cirrus-ci.com/task/4652887885217792) ([Github task](https://github.com/erikarvstedt/nix-bitcoin/runs/2748820954)).
Additionally, the test had already been successfully re-run by your force-push of the squashed branch.

**Comment by mmilata** [comment]
Rebased to master which now has charge-lnd package available in the pinned nixpkgs unstable.

**Comment by mmilata** [comment]
Force pushed again, now the configuration file check is performed at build time. I'm not planning to add anything else unless CI checks fail.

**Comment by nixbitcoin** [comment]
Tested with mainnet lnd and electrs.

See my [Fixups](https://github.com/nixbitcoin/nix-bitcoin/commits/charge-lnd-nb)

**Comment by mmilata** [comment]
Awesome, thanks @nixbitcoin! Squashed the fixup into the main commit.

**Review by nixbitcoin — APPROVED** [review]
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

ACK b666bb290307f7a594b3c04a7e3c9afa2ed19939
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCgAdFiEEiDOlIkszv4ojhh+OtgROy6La5dAFAmDtTo0ACgkQtgROy6La
5dABCQ//Y9hwlbbCEe+fSAbYt/W4Yu0e5qvkCWcnPU2mglquy4oZDL5Od5VWU8XT
y+ELfT6vKbmfwT6FsqNzzMTCiBlH6WS9i4ImVYB6/3UNObY3uEbcrPXY41sM+Ynj
KaFHZHHW9+LFCT7BuT4IPwzI3EHzgRv7yBTvvANYUfwnwugG0kO54YC6yq9lmldW
aWv7AXI3ye140vgsR/dXdTvRGCw2fqNYCDzFwC8w6oeqqTsHRM95gnPXtXPUUm3T
TP+Kh90jafErFaA4gvK/uMuhYtKOcugYUuPi+yZFdnT11lxXWSlIEQgtVJtJNDP4
OeTh6dT5wkyRVZh4HEATDgR3/tvsctFa6QanvMdysJtZmQLkuUx/7l9BLvjx7fx6
vg7AbgS4OS729v6hDPkLOb97KYNcfNAIzu4BdMXj/pKAd7ZTNKvOAQZxQEe8tSeV
32X19m/XDcSdgGzbslKX5zmgDuev+Qj7AqfNWdRIhtYwMSkNKgCIOiTQZQFbP4K/
XkjNdGPjdhoApH+nUSTMQQdIyEh8Ucah/xQLCHRhylPGF2Ats5Xb8HwDcd9Ydf5k
kq6wz6ykXNUjQurA4DbpLKAeUwRgud4ajHWw56qPKXIXhYC+rTJ8hNdQS4MIXxXa
IFwlT80MQirWdeeDy6A5r69E2FPhMpMHZ7TcCkBgYA60wnQVdBs=
=3I6Y
-----END PGP SIGNATURE-----
```

**Review by jonasnick — COMMENTED** [review]
looks good, thanks @mmilata and reviewers

**Pull request merged**
