### PR TITLE
lightning-loop: 0.12.0 -> 0.12.1

### PR DESCRIPTION
**Pull request by nixbitcoin**

### CODE REVIEW

**Comment by Kixunil** [comment]
Perhaps you could also make use of the new regtest server to implement tests. :)

**Comment by nixbitcoin** [comment]
We already are https://github.com/fort-nix/nix-bitcoin/blob/master/test/tests.py#L394

**Comment by Kixunil** [comment]
Yeah, that's a basic smoke test. I meant to actually try to execute loop in/out on regtest.

**Review by erikarvstedt — APPROVED** [review]
ACK cde9597fc44a89f1c58134dbeb9b7783d625d52c

**Pull request merged**
