### PR TITLE
Update CLBOSS, add test, add option for custom pkg

### PR DESCRIPTION
**Pull request by jonasnick**
CLBOSS 0.10 pays an enormous amount in rebalancing fees, which appears to be fixed in CLBOSS 0.11A. It is only a pre-release and apparently has a bug [that prevents rebalancing](https://github.com/ZmnSCPxj/clboss/blob/master/ChangeLog). Hopefully we don't have to wait very long for a new release soon (ping @zmnscpxj :]). The new module option allowing custom packages will help users to run CLBOSS master or test specific PRs.

### CODE REVIEW

**Comment by erikarvstedt** [comment]
[Minor fixup](https://github.com/erikarvstedt/nix-bitcoin/commits/update-clboss-ea).

**Comment by nixbitcoin** [comment]
ACK with @erikarvstedt fixup

**Comment by jonasnick** [comment]
Simpler indeed... Added fixup. Thanks.

**Review by erikarvstedt — APPROVED** [review]
ACK 7914405cede7acd6dab53f3e7965557b6d6c8636

**Pull request merged**
