### PR TITLE
lightning-loop: 0.11.0-beta -> 0.11.1-beta

### PR DESCRIPTION
**Pull request by nixbitcoin**
This PR updates lightning-loop.

@Guggero now also signs releases.

### CODE REVIEW

**Comment by erikarvstedt** [comment]
ACK 50372c9f2f97f372db3e24d93977cf3ec6114500

**Review by erikarvstedt — APPROVED** [review]

**Comment by guggero** [comment]
Just out of interest: Are you verifying both the git tag and the manifest signature? Because I didn't sign the release itself, but I created/pushed the git tag.

**Comment by nixbitcoin** [comment]
We're verifying the underlying tag signature with https://github.com/fort-nix/nix-bitcoin/pull/267/files#diff-52e85457747b4222c6148619c1ea53812c1a5492399b0e8c347523752862bd71L21

**Comment by guggero** [comment]
Oh wow, it was right there in the diff, I even looked at it but not close enough :see_no_evil:
Great stuff!

**Pull request merged**
