### PR TITLE
lnd: Use `lndinit` for wallet creation

### LINKED ISSUE #377: Simplify lnd-create-wallet
- [x] ~Instead of checking that wallet.dat exists, we can check if the state endpoint returns `NO_WALLET`.~ (EDIT: more complicated than just checking whether a file exists)
- [x] Instead of unlocking with the unlockwallet endpoint, we can set lnd's `wallet-unlock-password-file` flag. This would also require the `wallet-unlock-allow-create` flag because otherwise lnd fails if there is no wallet.
  By the way, the [commit that introduces this flag](https://github.com/lightningnetwork/lnd/commit/6ca38bc8150fcd299c633c4f44e187b486c76953) mentions a security issue where an unauthenticated attacker can inject a seed using the `initwallet` endpoint. But that's already an issue today (if netns isn't enabled). Afaik `initwallet` can be turned off after the [lndinit tool](https://github.com/lightningnetwork/lnd/pull/5150) is merged.
- [ ] Use [lndinit tool](https://github.com/lightningnetwork/lnd/pull/5150)  to create the wallet.

### PR DESCRIPTION
**Pull request by erikarvstedt**
Fixes #377

### CODE REVIEW

**Comment by nixbitcoin** [comment]
@mmilata Could you please review this LND specific change also?

**Comment by nixbitcoin** [comment]
[Fixup](https://github.com/nixbitcoin/nix-bitcoin/commits/lnd-lndinit-nb)

**Review by nixbitcoin — APPROVED** [review]
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

ACK a4a5c72b01e95a85db9ce50e62feea1c06a63811

Tested
* verified sha256
* nix-bitcoin test suite
* wallet recreation from seed
* wallet.db permissions
* manual wallet creation with lndinit
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCgAdFiEEiDOlIkszv4ojhh+OtgROy6La5dAFAmJK4zsACgkQtgROy6La
5dD3qg/7BXPR1YMHRTDC17l3qenokxG1D4Ckbv1juwQdMl34NeHS+P8Wh3YGxaQn
Ylx/OYL9hnvENWbUJ7Me7v9NlIv6Mdj9K+BT2t/n7ntbnT2w82EgyJgxfRwJJpFs
oKHUI2u+RVHnUvQDDPcbCKIkzOCNeJLDdU7YPUayhy0HrVIS3C/2j57s03kr+HoF
xYK8SYTj7q7B9PXuie3NHxYPf0klr5AgHuCU7I8R8rbGASxk2pzwkMsRE2Lmw+5J
qy6EAclKLo5wl6/gG1Ew66qMvy02+UJEKzWpVrMp4KYMOF83weZttnjHz8PRo89R
lskDTRXdi4F1ZxTddYfbkGk9Gvx7YGIbqd6sCRqyBMpfCZm82XaXCV0Sk2Q7lFZC
iQN1ZrOoDqQdkkG4t9E3IwuwfEvSU5NUU4YDbDkZY6KCUzNy5ys7zFpFtBua5LbK
ktVFvxky2TWUSsucAfSaDMI+SnJfM6wvK++AHhREVvyzERrrbs5NJjXPWDWzBTQV
H8bJXRm7g6qIXXA05RANqPc/7rotZWDDSgHos0cUPEJAijk3pY334UgmViP1OtOJ
dtyA+mrk/KL0nuAhmzXn1lZCjNzEoMZRaefOL5WDVBfoPs2tPlmqAKmkfwD61Yf/
bUEFbynWVlodbKTjU21aaTdzPDJq9gGTvxH85D1Mrh8JtAbYFAU=
=+yq/
-----END PGP SIGNATURE-----
```

**Review by mmilata — APPROVED** [review]
Haven't tested it but the changes look good to me. Appreciate the reduction of complexity of the shell scripts:)

**Review by jonasnick — COMMENTED** [review]
utACK a4a5c72b01e95a85db9ce50e62feea1c06a63811

**Pull request merged**
