### PR TITLE
update nixpkgs

### PR DESCRIPTION
**Pull request by jonasnick**
btcpayserver: 1.6.12 -> 1.7.1
bitcoind: 24.0 -> 24.0.1
clightning: 0.12.1 -> 22.11.1
lnd: 0.15.4-beta -> 0.15.5-beta
nbxplorer: 2.3.41 -> 2.3.49

### CODE REVIEW

**Review by erikarvstedt — APPROVED** [review]
ACK f70a018d46cbd4bf2b092f4afccb848c2d08051f

**Comment by jonasnick** [comment]
Thanks @prusnak! Will update nixpkgs again when the commits land in `nixpkgs-unstable`.

**Comment by jonasnick** [comment]
Updated nixpkgs again.

**Review by erikarvstedt — DISMISSED** [review]
ACK 875fac6862b166378be29958eef7a82d79fa416e

**Comment by nixbitcoin** [comment]
NACK

Getting

```
lightningd[2838651]: Refusing to irreversibly upgrade db from version 199 to 212 in non-final version v22.11.1 (use --database-upgrade=true to override)
```

**Comment by jonasnick** [comment]
Thanks @nixbitcoin and @ekimber! I added a commit that sets `database-upgrade=true` for version 22.11.1.

**Review by erikarvstedt — APPROVED** [review]
ACK d1b3a4617dd32ead2a549863565eec8ddd8b26a1

**Pull request merged**
