### PR TITLE
Add CLBOSS

### PR DESCRIPTION
**Pull request by nixbitcoin**
Adds @ZmnSCPxj's CLBOSS.
- Loaded via our clightning plugins mechanism
- Networked over tor with custom torify
- No PGP signatures available.

Closes https://github.com/fort-nix/nix-bitcoin/issues/273

### CODE REVIEW

**Comment by erikarvstedt** [comment]
Nice! [Fixups](https://github.com/erikarvstedt/nix-bitcoin/commits/clboss-ea).
It's okay for now that `clboss` is excluded from the tests because it significantly delays `clightning` startup when run offline. I've [reported this upstream](https://github.com/ZmnSCPxj/clboss/issues/49).

**Comment by nixbitcoin** [comment]
Squashed and added CLBOSS test todo

**Review by erikarvstedt — APPROVED** [review]
ACK 196e3c9dbba549db7b4f8591fd83fb1c0770ed1e

**Review by jonasnick — COMMENTED** [review]
Nice!

utACK 196e3c9dbba549db7b4f8591fd83fb1c0770ed1e

**Pull request merged**
