### PR TITLE
Update nixpkgs, spark-wallet and elementsd

### PR DESCRIPTION
**Pull request by jonasnick**
nixpkgs updates include
```
bitcoin: 0.18.1 -> 0.19.0.1
clightning: 0.7.3 -> 0.8.0
```

### CODE REVIEW

**Comment by erikarvstedt** [comment]
clightning 0.8.0 now stores the rpc socket file in `$dataDir/bitcoin` which breaks the old version of lightning-charge and parts of the clighting service.
I've added fixes [here](https://github.com/erikarvstedt/nix-bitcoin/commits/pr-134), applied on top of #133 and this PR.
But let's merge #133 first...

**Comment by jonasnick** [comment]
rebased

**Comment by erikarvstedt** [comment]
Rebased [my fixes](https://github.com/erikarvstedt/nix-bitcoin/commits/pr-134).

**Comment by jonasnick** [comment]
Thanks for your fixes. So much easier to test PRs like this now :)

**Pull request merged**
