### PR TITLE
WIP: Support nixpkgs unstable

### PR DESCRIPTION
**Pull request by erikarvstedt**
This PR adds support for nixpkgs unstable.

The following lower-priority features haven't yet been fixed and are disabled:
- `services.clightning.plugins.prometheus` (build failure)
- `services.liquidd` (build failure)
- `services.joinmarket-ob-watcher` (service failure)
- `nix-bitcoin.netns-isolation` (service failure)

### CODE REVIEW

**Comment by nixbitcoin** [comment]
We should not delete `security.nix`! The dbus firewall is an essential mitigation for https://github.com/fort-nix/nix-bitcoin/pull/213

**Comment by erikarvstedt** [comment]
Because `hidepid` has been removed in NixOS, the `systemctl status` info is now always available via `/proc`. So there's no further use in restricting `systemctl status`.

**Comment by erikarvstedt** [comment]
The underlying reason for the removal is [related to systemd](https://github.com/systemd/systemd/issues/12955).
But it seems there are some efforts in systemd to bring it back.

**Comment by prusnak** [comment]
This PR should be broken into smaller self-contained PRs, otherwise it will be left here open forever.

**Comment by jonasnick** [comment]
@prusnak Erik mentioned to me that he'd continue working on this PR some time in the coming weeks.

**Comment by erikarvstedt** [comment]
Superseded by https://github.com/fort-nix/nix-bitcoin/pull/374.

**Pull request closed without merging**
