### PR TITLE
examples: Fix shell on non-Linux systems

### LINKED ISSUE #398: Fails to run example on macOS
I am trying to run the examples on my Macbook Pro.

I was able to successfully install Nix. But when I try to run the example I get this error:

```
macbook-pro:work yzernik$ git clone https://github.com/fort-nix/nix-bitcoin
Cloning into 'nix-bitcoin'...
remote: Enumerating objects: 6198, done.
remote: Counting objects: 100% (974/974), done.
remote: Compressing objects: 100% (483/483), done.
remote: Total 6198 (delta 591), reused 823 (delta 472), pack-reused 5224
Receiving objects: 100% (6198/6198), 2.25 MiB | 6.64 MiB/s, done.
Resolving deltas: 100% (4067/4067), done.
macbook-pro:work yzernik$ cd nix-bitcoin/examples/
macbook-pro:examples yzernik$ nix-shell
unpacking 'https://github.com/nixos/nixpkgs/archive/6120ac5cd201f6cb593d1b80e861be0342495be9.tar.gz'...
error: Package ‘shadow-4.8.1’ in /nix/store/hkf8b2b79xj83ns6r6a4y1axkfr13krj-source/pkgs/os-specific/linux/shadow/default.nix:87 is not supported on ‘x86_64-darwin’, refusing to evaluate.

a) To temporarily allow packages that are unsupported for this system, you can use an environment variable
   for a single invocation of the nix tools.

     $ export NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1

b) For `nixos-rebuild` you can set
  { nixpkgs.config.allowUnsupportedSystem = true; }
in configuration.nix to override this.

c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowUnsupportedSystem = true; }
to ~/.config/nixpkgs/config.nix.

(use '--show-trace' to show detailed location information)
```

I also tried setting the environment variable, but then there's a different error:
```
macbook-pro:examples yzernik$ export NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1
macbook-pro:examples yzernik$ nix-shell
error: cannot coerce null to a string, at /Users/yzernik/work/nix-bitcoin/pkgs/extra-container/default.nix:15:18
(use '--show-trace' to show detailed location information)
```

Does this mean that macOS is not supported?

### PR DESCRIPTION
**Pull request by erikarvstedt**
extra-container is not supported on these systems.

Fixes #398

### CODE REVIEW

**Review by jonasnick — DISMISSED** [review]
ACK c8e97c23d0a9c0d418a04c1cf6f5fff5362b8b63

@yzernik does this work for you? The QEMU VM examples should work, and the container examples should error with something like `./deploy-container.sh: line 94: extra-container: command not found`.

**Comment by yzernik** [comment]
@jonasnick  nix-shell is working now, but I am getting a different error when I run `./deploy-qemu-vm.sh`:

```
jonathans-mbp:examples yzernik$ nix-shell
these paths will be fetched (164.74 MiB download, 821.64 MiB unpacked):
  /nix/store/015rgxn5xx5awkz48yhh9c9n1bsvvivm-libiconv-50
  /nix/store/039jf73378jkyd9m93d4ffgbvak1yang-xz-5.2.5-bin
  /nix/store/0cgmjzpv8xy2ll3z1wwpnj5js58ddp07-libcxx-7.1.0
  /nix/store/13v7wr4lifdyyn979w3ql273a35fmaj8-bzip2-1.0.6.0.2-bin
  /nix/store/17h23im7ln8cqv87hhmcw339vk1siwg3-gzip-1.10
  /nix/store/1ji5qnjzb7jb0ci74wlgwia5bkd44i1m-libkrb5-1.18
  /nix/store/20gjynmn10aj4haxnbzhyhgdgid81cqd-readline-7.0p5
  /nix/store/2m6xq88is0hwychgsphp4qrib926ac1v-openssl-1.1.1l
  /nix/store/2sm876fdnn1vy5aa6c82ynal7h73aj10-gnugrep-3.6
  /nix/store/2xcqi5rqzswhvl0yf327lvxnns60dg0z-brotli-1.0.9-lib
  /nix/store/3saax6q1s9im5p80nxhdqpjmw3g4nzg8-curl-7.76.1
  /nix/store/42ac4p1wizi87ys3262r07gm1fikx76h-clang-7.1.0-lib
  /nix/store/4jxs387h75j93a9cf3yv44ns1h73lxr7-compiler-rt-libc-7.1.0-dev
  /nix/store/50ihi53j4ghl34rlfsjxcv30xkrj340v-cctools-binutils-darwin-949.0.1
  /nix/store/5n4n1k1j51p7qyzp9bkgs60n9lzwy1vl-clang-7.1.0
  /nix/store/5wr0yfwcmggwj3nn2mkxb5aiz8iqkvcj-nghttp2-1.43.0-lib
  /nix/store/6jvb0gz9j5lz3cp0as9537ic46p8ymkh-bash-interactive-4.4-p23-dev
  /nix/store/6p1mr7avpnni6n7ssxqjfj7fa4sy00x0-openssl-1.1.1l
  /nix/store/75d82drckbdj5m9iizx62qcp64ivqh05-adv_cmds-119-locale
  /nix/store/79q6vp06aj2p550f2wgn9zywywm6pmir-libcxxabi-7.1.0
  /nix/store/7rx1kz1fj171a7s5dln0scygqhbnghbk-expand-response-params
  /nix/store/838avl1z11sk6z7jn7f2lw7a1gba9ldc-ICU-66108
  /nix/store/8f1c6yy0n6dkghghfainnb6vx8lfszjj-libssh2-1.9.0
  /nix/store/8n7pgw5wpqrp66a8djndaw4cndbcf9d8-bash-interactive-4.4-p23-man
  /nix/store/9dxa759ivj70gxnby17ddzimmrk46mdp-pcre-8.44
  /nix/store/9lj6bc2qnxhv9blg994dgxy6dd7m22vc-bash-interactive-4.4-p23-doc
  /nix/store/afpdl5r9jnb8bx42nzpqi0c6g1flwldg-Libsystem-1238.60.2
  /nix/store/ck8k15nvvdvhcl18bbkjp0kmqasavj02-gawk-5.1.0
  /nix/store/cpgyi9khbv1yg2i22vg0zhmsnif9aih9-bash-4.4-p23
  /nix/store/cr4nsw7jkyd6b8ghz8yr95lwqhzgp6r3-coreutils-8.32
  /nix/store/dimrkizsipd8iakwswlh92s8fi96r63l-swift-corefoundation
  /nix/store/dnzb4zfcyyxbwgz9s25xhxw54fzwsxm7-gettext-0.21
  /nix/store/dq2mhj4b820xwbg0rsy08fzn2n0n2a4c-bash-interactive-4.4-p23-info
  /nix/store/fv8npqw36y2rv6ij21svjqrxxf1h18n7-gnused-4.8
  /nix/store/fvanap2bl0pz2sis7xjyx83i113p2s9x-ed-1.17
  /nix/store/fypvk62zfd53x1galmw3vw82v09i9zsi-cctools-port-949.0.1
  /nix/store/g49a29j04zgzw5xa18y47134cq6yc2bc-gnutar-1.34
  /nix/store/g8fbhc5bn0mi29gw3jhxm4hrlif00nlz-brotli-1.0.9-lib
  /nix/store/gb9nkla1b2zplgbn7j01q7l8hswgwcnb-xz-5.2.5
  /nix/store/h5qh4vkdvn32gpcpl5ai7h9kxkhj5qym-stdenv-darwin
  /nix/store/hi8i2a2f9hai47sakmyrkh39pvhaqfn3-findutils-4.7.0
  /nix/store/hjhfc24rbrkcw4s6339haywj3agf6ib9-ncurses-6.2
  /nix/store/i0zac1vw0ra6g2mg701m3kc9xbi24lgg-zlib-1.2.11
  /nix/store/i8rksi0pqzcbmsfs48kwp5nvih8mfn4a-bzip2-1.0.6.0.2
  /nix/store/j1qrmvjzjzihpvfh997xvy8myrl2p358-cctools-binutils-darwin-wrapper-949.0.1
  /nix/store/j4bf4z7zrd461r4bjiwsrnzc5am0jv9a-bash-4.4-p23
  /nix/store/jhm13nlylakqfkgrj304lp6gh4l537rw-figlet-2.2.5
  /nix/store/jjfiw9s3g7qbz6y96v8vfb4282rg4791-libcxx-7.1.0
  /nix/store/jnq7mac7g26ja39rca2nnbvxnm1d3vvs-clang-wrapper-7.1.0
  /nix/store/k5i7ralzb1w0jx3fyn8q9n80kwv16l33-swift-corefoundation
  /nix/store/kr73g0f7k4ckvss51jj11crxr4jy7iax-diffutils-3.7
  /nix/store/kvvpk2vdlh4pc8qyfxcd1rlzyr4zb3bp-libssh2-1.9.0
  /nix/store/l2z0g2477zr9b2m2q9jjz19iqak1b3nl-patch-2.7.6
  /nix/store/n89si82dkslcqmlmsn4vi0lw2v34ibmg-gnumake-4.3
  /nix/store/nqfyfv5lq0n00iqakzcpbl5cq2dkwdz8-libxml2-2.9.12
  /nix/store/pjnycbp1q1x6ab2n185ln7kkmgzz80mx-llvm-7.1.0-lib
  /nix/store/r92p16irq0w4flscy19h3cs0yyzcz8y0-libcxxabi-7.1.0
  /nix/store/rcvw053p9bim788lvvjyry3saw84m0j8-compiler-rt-libc-7.1.0
  /nix/store/rq6iahdbacw3gzyf4h7b5j77i5amkya6-ncurses-6.2
  /nix/store/rsjpna1d06qyqmszsm9w5pr58z8cg8fy-libffi-3.3
  /nix/store/sa6djm32xxqkl96fggjn7pv4bfqbc2ij-binutils-2.35.1
  /nix/store/shg7n21w7hrj0c7gjk7r8cd82vsayycs-gmp-6.2.1
  /nix/store/svdv7yxxsym1sslxj4p5278k4dv17p6p-curl-7.76.1
  /nix/store/v544w7s6qk73g9ysl1q4qcx6j7wj36m6-libxml2-2.9.12
  /nix/store/wh5hnzk0pkiczyn837qg6gy6yz671lih-zlib-1.2.11
  /nix/store/wil7lqvyfb18hkdv0bdrf5h0f9y5v9lm-ICU-66108
  /nix/store/x0r180c6xm8zgfnczhi27831ly56k888-nghttp2-1.43.0-lib
  /nix/store/x2azxialhs6d0ni0g0wx3spnwqvinzis-bash-interactive-4.4-p23
  /nix/store/xfrv2iqk2838f6h36nl77xmcpiajp41s-libtapi-1100.0.11
  /nix/store/xzi13qb8hvj4i32ra5nvy49b3xdxfj0s-llvm-7.1.0
  /nix/store/y3zjykrbfnw7cbyvbgyg4p9b32jhcigy-libcxx-7.1.0-dev
  /nix/store/yyc2gy0hmyl9q86l8600s9dyspyzh92v-libcxxabi-7.1.0-dev
  /nix/store/z31hmk06a669vhjaj6ahn5x2i73l2bsy-libkrb5-1.18
  /nix/store/zhfzmfl57q33zc3hw8k3a4gl5hbymzwp-Libsystem-1238.60.2
copying path '/nix/store/cpgyi9khbv1yg2i22vg0zhmsnif9aih9-bash-4.4-p23' from 'https://cache.nixos.org'...
copying path '/nix/store/afpdl5r9jnb8bx42nzpqi0c6g1flwldg-Libsystem-1238.60.2' from 'https://cache.nixos.org'...
copying path '/nix/store/zhfzmfl57q33zc3hw8k3a4gl5hbymzwp-Libsystem-1238.60.2' from 'https://cache.nixos.org'...
copying path '/nix/store/75d82drckbdj5m9iizx62qcp64ivqh05-adv_cmds-119-locale' from 'https://cache.nixos.org'...
copying path '/nix/store/j4bf4z7zrd461r4bjiwsrnzc5am0jv9a-bash-4.4-p23' from 'https://cache.nixos.org'...
copying path '/nix/store/9lj6bc2qnxhv9blg994dgxy6dd7m22vc-bash-interactive-4.4-p23-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/dq2mhj4b820xwbg0rsy08fzn2n0n2a4c-bash-interactive-4.4-p23-info' from 'https://cache.nixos.org'...
copying path '/nix/store/8n7pgw5wpqrp66a8djndaw4cndbcf9d8-bash-interactive-4.4-p23-man' from 'https://cache.nixos.org'...
copying path '/nix/store/2xcqi5rqzswhvl0yf327lvxnns60dg0z-brotli-1.0.9-lib' from 'https://cache.nixos.org'...
copying path '/nix/store/g8fbhc5bn0mi29gw3jhxm4hrlif00nlz-brotli-1.0.9-lib' from 'https://cache.nixos.org'...
copying path '/nix/store/i8rksi0pqzcbmsfs48kwp5nvih8mfn4a-bzip2-1.0.6.0.2' from 'https://cache.nixos.org'...
copying path '/nix/store/fvanap2bl0pz2sis7xjyx83i113p2s9x-ed-1.17' from 'https://cache.nixos.org'...
copying path '/nix/store/13v7wr4lifdyyn979w3ql273a35fmaj8-bzip2-1.0.6.0.2-bin' from 'https://cache.nixos.org'...
copying path '/nix/store/7rx1kz1fj171a7s5dln0scygqhbnghbk-expand-response-params' from 'https://cache.nixos.org'...
copying path '/nix/store/ck8k15nvvdvhcl18bbkjp0kmqasavj02-gawk-5.1.0' from 'https://cache.nixos.org'...
copying path '/nix/store/n89si82dkslcqmlmsn4vi0lw2v34ibmg-gnumake-4.3' from 'https://cache.nixos.org'...
copying path '/nix/store/fv8npqw36y2rv6ij21svjqrxxf1h18n7-gnused-4.8' from 'https://cache.nixos.org'...
copying path '/nix/store/17h23im7ln8cqv87hhmcw339vk1siwg3-gzip-1.10' from 'https://cache.nixos.org'...
copying path '/nix/store/79q6vp06aj2p550f2wgn9zywywm6pmir-libcxxabi-7.1.0' from 'https://cache.nixos.org'...
copying path '/nix/store/r92p16irq0w4flscy19h3cs0yyzcz8y0-libcxxabi-7.1.0' from 'https://cache.nixos.org'...
copying path '/nix/store/0cgmjzpv8xy2ll3z1wwpnj5js58ddp07-libcxx-7.1.0' from 'https://cache.nixos.org'...
copying path '/nix/store/jjfiw9s3g7qbz6y96v8vfb4282rg4791-libcxx-7.1.0' from 'https://cache.nixos.org'...
copying path '/nix/store/wil7lqvyfb18hkdv0bdrf5h0f9y5v9lm-ICU-66108' from 'https://cache.nixos.org'...
copying path '/nix/store/838avl1z11sk6z7jn7f2lw7a1gba9ldc-ICU-66108' from 'https://cache.nixos.org'...
copying path '/nix/store/rcvw053p9bim788lvvjyry3saw84m0j8-compiler-rt-libc-7.1.0' from 'https://cache.nixos.org'...
copying path '/nix/store/shg7n21w7hrj0c7gjk7r8cd82vsayycs-gmp-6.2.1' from 'https://cache.nixos.org'...
copying path '/nix/store/4jxs387h75j93a9cf3yv44ns1h73lxr7-compiler-rt-libc-7.1.0-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/cr4nsw7jkyd6b8ghz8yr95lwqhzgp6r3-coreutils-8.32' from 'https://cache.nixos.org'...
copying path '/nix/store/y3zjykrbfnw7cbyvbgyg4p9b32jhcigy-libcxx-7.1.0-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/kr73g0f7k4ckvss51jj11crxr4jy7iax-diffutils-3.7' from 'https://cache.nixos.org'...
copying path '/nix/store/hi8i2a2f9hai47sakmyrkh39pvhaqfn3-findutils-4.7.0' from 'https://cache.nixos.org'...
copying path '/nix/store/yyc2gy0hmyl9q86l8600s9dyspyzh92v-libcxxabi-7.1.0-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/rsjpna1d06qyqmszsm9w5pr58z8cg8fy-libffi-3.3' from 'https://cache.nixos.org'...
copying path '/nix/store/015rgxn5xx5awkz48yhh9c9n1bsvvivm-libiconv-50' from 'https://cache.nixos.org'...
copying path '/nix/store/1ji5qnjzb7jb0ci74wlgwia5bkd44i1m-libkrb5-1.18' from 'https://cache.nixos.org'...
copying path '/nix/store/dnzb4zfcyyxbwgz9s25xhxw54fzwsxm7-gettext-0.21' from 'https://cache.nixos.org'...
copying path '/nix/store/z31hmk06a669vhjaj6ahn5x2i73l2bsy-libkrb5-1.18' from 'https://cache.nixos.org'...
copying path '/nix/store/g49a29j04zgzw5xa18y47134cq6yc2bc-gnutar-1.34' from 'https://cache.nixos.org'...
copying path '/nix/store/hjhfc24rbrkcw4s6339haywj3agf6ib9-ncurses-6.2' from 'https://cache.nixos.org'...
copying path '/nix/store/rq6iahdbacw3gzyf4h7b5j77i5amkya6-ncurses-6.2' from 'https://cache.nixos.org'...
copying path '/nix/store/xfrv2iqk2838f6h36nl77xmcpiajp41s-libtapi-1100.0.11' from 'https://cache.nixos.org'...
copying path '/nix/store/5wr0yfwcmggwj3nn2mkxb5aiz8iqkvcj-nghttp2-1.43.0-lib' from 'https://cache.nixos.org'...
copying path '/nix/store/fypvk62zfd53x1galmw3vw82v09i9zsi-cctools-port-949.0.1' from 'https://cache.nixos.org'...
copying path '/nix/store/x0r180c6xm8zgfnczhi27831ly56k888-nghttp2-1.43.0-lib' from 'https://cache.nixos.org'...
copying path '/nix/store/2m6xq88is0hwychgsphp4qrib926ac1v-openssl-1.1.1l' from 'https://cache.nixos.org'...
copying path '/nix/store/6p1mr7avpnni6n7ssxqjfj7fa4sy00x0-openssl-1.1.1l' from 'https://cache.nixos.org'...
copying path '/nix/store/l2z0g2477zr9b2m2q9jjz19iqak1b3nl-patch-2.7.6' from 'https://cache.nixos.org'...
copying path '/nix/store/9dxa759ivj70gxnby17ddzimmrk46mdp-pcre-8.44' from 'https://cache.nixos.org'...
copying path '/nix/store/gb9nkla1b2zplgbn7j01q7l8hswgwcnb-xz-5.2.5' from 'https://cache.nixos.org'...
copying path '/nix/store/2sm876fdnn1vy5aa6c82ynal7h73aj10-gnugrep-3.6' from 'https://cache.nixos.org'...
copying path '/nix/store/039jf73378jkyd9m93d4ffgbvak1yang-xz-5.2.5-bin' from 'https://cache.nixos.org'...
copying path '/nix/store/i0zac1vw0ra6g2mg701m3kc9xbi24lgg-zlib-1.2.11' from 'https://cache.nixos.org'...
copying path '/nix/store/wh5hnzk0pkiczyn837qg6gy6yz671lih-zlib-1.2.11' from 'https://cache.nixos.org'...
copying path '/nix/store/sa6djm32xxqkl96fggjn7pv4bfqbc2ij-binutils-2.35.1' from 'https://cache.nixos.org'...
copying path '/nix/store/8f1c6yy0n6dkghghfainnb6vx8lfszjj-libssh2-1.9.0' from 'https://cache.nixos.org'...
copying path '/nix/store/kvvpk2vdlh4pc8qyfxcd1rlzyr4zb3bp-libssh2-1.9.0' from 'https://cache.nixos.org'...
copying path '/nix/store/svdv7yxxsym1sslxj4p5278k4dv17p6p-curl-7.76.1' from 'https://cache.nixos.org'...
copying path '/nix/store/3saax6q1s9im5p80nxhdqpjmw3g4nzg8-curl-7.76.1' from 'https://cache.nixos.org'...
copying path '/nix/store/nqfyfv5lq0n00iqakzcpbl5cq2dkwdz8-libxml2-2.9.12' from 'https://cache.nixos.org'...
copying path '/nix/store/v544w7s6qk73g9ysl1q4qcx6j7wj36m6-libxml2-2.9.12' from 'https://cache.nixos.org'...
copying path '/nix/store/pjnycbp1q1x6ab2n185ln7kkmgzz80mx-llvm-7.1.0-lib' from 'https://cache.nixos.org'...
copying path '/nix/store/dimrkizsipd8iakwswlh92s8fi96r63l-swift-corefoundation' from 'https://cache.nixos.org'...
copying path '/nix/store/5n4n1k1j51p7qyzp9bkgs60n9lzwy1vl-clang-7.1.0' from 'https://cache.nixos.org'...
copying path '/nix/store/42ac4p1wizi87ys3262r07gm1fikx76h-clang-7.1.0-lib' from 'https://cache.nixos.org'...
copying path '/nix/store/xzi13qb8hvj4i32ra5nvy49b3xdxfj0s-llvm-7.1.0' from 'https://cache.nixos.org'...
copying path '/nix/store/20gjynmn10aj4haxnbzhyhgdgid81cqd-readline-7.0p5' from 'https://cache.nixos.org'...
copying path '/nix/store/50ihi53j4ghl34rlfsjxcv30xkrj340v-cctools-binutils-darwin-949.0.1' from 'https://cache.nixos.org'...
copying path '/nix/store/x2azxialhs6d0ni0g0wx3spnwqvinzis-bash-interactive-4.4-p23' from 'https://cache.nixos.org'...
copying path '/nix/store/j1qrmvjzjzihpvfh997xvy8myrl2p358-cctools-binutils-darwin-wrapper-949.0.1' from 'https://cache.nixos.org'...
copying path '/nix/store/6jvb0gz9j5lz3cp0as9537ic46p8ymkh-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/jnq7mac7g26ja39rca2nnbvxnm1d3vvs-clang-wrapper-7.1.0' from 'https://cache.nixos.org'...
copying path '/nix/store/k5i7ralzb1w0jx3fyn8q9n80kwv16l33-swift-corefoundation' from 'https://cache.nixos.org'...
copying path '/nix/store/jhm13nlylakqfkgrj304lp6gh4l537rw-figlet-2.2.5' from 'https://cache.nixos.org'...
copying path '/nix/store/h5qh4vkdvn32gpcpl5ai7h9kxkhj5qym-stdenv-darwin' from 'https://cache.nixos.org'...
       _           _     _ _            _       
 _ __ (_)_  __    | |__ (_) |_ ___ ___ (_)_ __  
| '_ \| \ \/ /____| '_ \| | __/ __/ _ \| | '_ \ 
| | | | |>  <_____| |_) | | || (_| (_) | | | | |
|_| |_|_/_/\_\    |_.__/|_|\__\___\___/|_|_| |_|
                                                
Enter "h" or "help" for documentation.

[nix-shell:~/work/nix-bitcoin/examples]$ 

[nix-shell:~/work/nix-bitcoin/examples]$ 

[nix-shell:~/work/nix-bitcoin/examples]$ ./deploy-qemu-vm.sh
Building VM
error: assertion (stdenv).isLinux failed at /nix/store/hkf8b2b79xj83ns6r6a4y1axkfr13krj-source/pkgs/os-specific/linux/kernel/generic.nix:66:1
(use '--show-trace' to show detailed location information)

```

**Comment by erikarvstedt** [comment]
Unfortunately, the NixOS qemu VM framework which is used by the examples doesn't work on macOS. But there are [efforts to fix this](https://github.com/NixOS/nixpkgs/issues/108984). I've now mentioned this in the examples README.
The examples shell is still useful on non-Linux systems for the deployment commands which **really** should work across platforms.

**Review by jonasnick — APPROVED** [review]
Ah, TIL.

ACK 46af0b1a8d4297af51e13d77e10e849b5cc18eab

**Pull request merged**
