### PR TITLE
update nixpkgs

### PR DESCRIPTION
**Pull request by jonasnick**
Includes
bitcoin: 0.21.0 -> 0.21.1

### CODE REVIEW

**Comment by erikarvstedt** [comment]
[One extra commit](https://github.com/erikarvstedt/nix-bitcoin/commits/update-nixpkgs18-ea).

**Comment by nixbitcoin** [comment]
No more pgp verification :(

**Review by nixbitcoin — APPROVED** [review]
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

ACK 7ae0a387018f3fdd9fc5dc9c13aa2186b46f592e
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCgAdFiEEiDOlIkszv4ojhh+OtgROy6La5dAFAmCROCoACgkQtgROy6La
5dBrGw//WsGGJKpP9PCLVJ8WvGauWZOGyXYM0yHdVE4bMu3+8WHT5IfcMA04GGWo
G2mcCWGA+X2l+J+qsFPChXYigzeYlbmKv1G1MNthsqUiCqcB54DLLD/UFQthG545
fTOEWApIgDLMCcy7X/7iZ00yMe+heBEOjiuJwxHiJldtD9Ja424LMHs0eKrTop7t
Ib5dGhHxXEm1wU+sskMkDgzFHzBqfSBGTs/ckHI+SovXOrZST0NpS+yOSi3ySeeE
LL6HwxZRlX/IVmDYqbuU8lhxvWPb9Vsn6q8tPFSYqln/A02yTxSgwtyzXla3Zjv3
Rfzg66zjo4MGXgIKTZ3a7jz6PFNQwZj8PfndWuD/FC6Tan7cwwtJA4PE0uukjBeV
xzicKTQOjRHo6yLfGxuIGsSTdUpxjBIidjHTSgdm0xESogqbbgwY0T0/+Y6MvsEy
5f8VcLxl0NQrTMBy/w0neB8qsOfB+YJ74qDpZ5Mto3YK1mQV5ckBmxtigO8vhT0Q
iGCJHTQvgjaix39PyyGbcsGDgkxuWTS3aOw9keXMgi3mrN1xYyZ5lSSzsavaTV+X
e3rbEYHQhF/vs84paj2XL0CfIeswqOInGgxn9/YKe7trsX48CVDt12BYhCRek/OZ
0W/ipluCGXeVm9tHRAtWl4MHkUb70FTVRUnjNN1Ls/9SrN55Eq8=
=p/Pl
-----END PGP SIGNATURE-----
```

**Review by erikarvstedt — APPROVED** [review]
ACK 7ae0a387018f3fdd9fc5dc9c13aa2186b46f592e

**Pull request merged**
