### PR TITLE
Add nixos-search support

### PR DESCRIPTION
**Pull request by erikarvstedt**
This adds compatibility with the [doc generators](https://github.com/NixOS/nixos-search/) for https://search.nixos.org/flakes, the options and packages index for the Nix flake ecosystem.

### CODE REVIEW

**Comment by nixbitcoin** [comment]
Read through the PR, all changes seem benign. Is there a way to check the functionality or do we have to wait for the [nixos-search](https://search.nixos.org/flakes) PR for that?

**Comment by erikarvstedt** [comment]
Run `nix run ./test/nixos-search#flake-info -- --json flake ./. | jq` from the repo root to see the data that will be used by the search interface.
You can run the nixos-search web interface [locally](https://github.com/NixOS/nixos-search/#development), but feeding it flake metadata will probably require extra steps.

**Comment by erikarvstedt** [comment]
Rebased.

**Review by nixbitcoin — DISMISSED** [review]
light ACK e29e32ac12f8a698b9bfd6c2b1c51fdc82fa6da2

Hard for me to understand since I am not familiar with NixOS doc generation. Performed random comparisons of module descriptions and examples from `nix run ./test/nixos-search#flake-info -- --json flake ./. | jq` and source files.

**Review by nixbitcoin — APPROVED** [review]
reACK 5e59c784ed2c7092d7ab8df365a56e7a4bd05dbe

**Pull request merged**
